
// This file has been generated by the GUI designer. Do not modify.
namespace ocmgtk
{
	public partial class ModifyCacheDialog
	{
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.Table table2;
		
		private global::Gtk.Entry codeEntry;
		
		private global::Gtk.Frame frame3;
		
		private global::Gtk.Alignment GtkAlignment2;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Image image46;
		
		private global::Gtk.Button corrButton;
		
		private global::Gtk.Label label3;
		
		private global::ocmgtk.LocationWidget coordEntry;
		
		private global::Gtk.Label GtkLabel2;
		
		private global::Gtk.Frame frame4;
		
		private global::Gtk.Alignment GtkAlignment3;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView descriptionEntry;
		
		private global::Gtk.Label GtkLabel3;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.ComboBox typeEntry;
		
		private global::Gtk.Entry urlEntry;
		
		private global::Gtk.Entry urlNameEntry;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Table table3;
		
		private global::Gtk.ComboBox diffEntry;
		
		private global::Gtk.Frame frame5;
		
		private global::Gtk.Alignment GtkAlignment4;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.TextView shortDescEntry;
		
		private global::Gtk.Label GtkLabel4;
		
		private global::Gtk.Frame frame6;
		
		private global::Gtk.Alignment GtkAlignment5;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		
		private global::Gtk.TextView longDescEntry;
		
		private global::Gtk.Label GtkLabel5;
		
		private global::Gtk.Frame frame7;
		
		private global::Gtk.Alignment GtkAlignment6;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow3;
		
		private global::Gtk.TextView hintEntry;
		
		private global::Gtk.Label GtkLabel6;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.Label label14;
		
		private global::Gtk.Label label15;
		
		private global::Gtk.Entry nameEntry;
		
		private global::Gtk.ComboBox terrEntry;
		
		private global::Gtk.Label name;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.Frame frame8;
		
		private global::Gtk.Alignment GtkAlignment7;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.Entry cacheIDEntry;
		
		private global::Gtk.Label label19;
		
		private global::Gtk.Label label20;
		
		private global::Gtk.Label label21;
		
		private global::Gtk.Label label22;
		
		private global::Gtk.Entry ownerEntry;
		
		private global::Gtk.Entry ownerIDEntry;
		
		private global::Gtk.Entry placedByEntry;
		
		private global::Gtk.Label GtkLabel;
		
		private global::Gtk.Frame frame9;
		
		private global::Gtk.Alignment GtkAlignment8;
		
		private global::Gtk.Table table4;
		
		private global::Gtk.Label label23;
		
		private global::Gtk.Label label24;
		
		private global::Gtk.Label label25;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Entry udata1Entry;
		
		private global::Gtk.Entry uData2Entry;
		
		private global::Gtk.Entry uData3Entry;
		
		private global::Gtk.Entry uData4Entry;
		
		private global::Gtk.Label GtkLabel8;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ocmgtk.ModifyCacheDialog
			this.WidthRequest = 650;
			this.HeightRequest = 550;
			this.Name = "ocmgtk.ModifyCacheDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Add/Modify Geocache...");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(6));
			// Internal child ocmgtk.ModifyCacheDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			this.notebook1.TabPos = ((global::Gtk.PositionType)(0));
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.table2 = new global::Gtk.Table (((uint)(6)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			this.table2.BorderWidth = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.codeEntry = new global::Gtk.Entry ();
			this.codeEntry.CanFocus = true;
			this.codeEntry.Name = "codeEntry";
			this.codeEntry.IsEditable = true;
			this.codeEntry.InvisibleChar = '•';
			this.table2.Add (this.codeEntry);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2 [this.codeEntry]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.image46 = new global::Gtk.Image ();
			this.image46.Name = "image46";
			this.image46.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-info", global::Gtk.IconSize.Button);
			this.hbox1.Add (this.image46);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image46]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.corrButton = new global::Gtk.Button ();
			this.corrButton.CanFocus = true;
			this.corrButton.Name = "corrButton";
			this.corrButton.FocusOnClick = false;
			this.corrButton.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child corrButton.Gtk.Container+ContainerChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Use <span fgcolor=\"blue\">corrected coordinates</span> to prevent GPX imports from overwriting the cache location");
			this.label3.UseMarkup = true;
			this.corrButton.Add (this.label3);
			this.hbox1.Add (this.corrButton);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.corrButton]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.coordEntry = null;
			this.vbox2.Add (this.coordEntry);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.coordEntry]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.GtkAlignment2.Add (this.vbox2);
			this.frame3.Add (this.GtkAlignment2);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Location</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel2;
			this.table2.Add (this.frame3);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.frame3]));
			w10.TopAttach = ((uint)(4));
			w10.BottomAttach = ((uint)(5));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.frame4 = new global::Gtk.Frame ();
			this.frame4.Name = "frame4";
			this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame4.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.descriptionEntry = new global::Gtk.TextView ();
			this.descriptionEntry.CanFocus = true;
			this.descriptionEntry.Name = "descriptionEntry";
			this.GtkScrolledWindow.Add (this.descriptionEntry);
			this.vbox3.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow]));
			w12.Position = 0;
			this.GtkAlignment3.Add (this.vbox3);
			this.frame4.Add (this.GtkAlignment3);
			this.GtkLabel3 = new global::Gtk.Label ();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Waypoint Description</b>");
			this.GtkLabel3.UseMarkup = true;
			this.frame4.LabelWidget = this.GtkLabel3;
			this.table2.Add (this.frame4);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table2 [this.frame4]));
			w15.TopAttach = ((uint)(5));
			w15.BottomAttach = ((uint)(6));
			w15.RightAttach = ((uint)(2));
			// Container child table2.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xalign = 0F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("URL:");
			this.table2.Add (this.label11);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table2 [this.label11]));
			w16.TopAttach = ((uint)(2));
			w16.BottomAttach = ((uint)(3));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xalign = 0F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("URL Name:");
			this.table2.Add (this.label12);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table2 [this.label12]));
			w17.TopAttach = ((uint)(3));
			w17.BottomAttach = ((uint)(4));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Cache Type:");
			this.table2.Add (this.label7);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table2 [this.label7]));
			w18.TopAttach = ((uint)(1));
			w18.BottomAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xalign = 0F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Cache Code:");
			this.table2.Add (this.label8);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table2 [this.label8]));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.typeEntry = global::Gtk.ComboBox.NewText ();
			this.typeEntry.AppendText (global::Mono.Unix.Catalog.GetString ("Generic"));
			this.typeEntry.AppendText (global::Mono.Unix.Catalog.GetString ("Traditional Cache"));
			this.typeEntry.AppendText (global::Mono.Unix.Catalog.GetString ("Unknown Cache"));
			this.typeEntry.AppendText (global::Mono.Unix.Catalog.GetString ("Multi-Cache"));
			this.typeEntry.AppendText (global::Mono.Unix.Catalog.GetString ("Earthcache"));
			this.typeEntry.AppendText (global::Mono.Unix.Catalog.GetString ("Eventcache"));
			this.typeEntry.AppendText (global::Mono.Unix.Catalog.GetString ("Letterbox Hybrid"));
			this.typeEntry.AppendText (global::Mono.Unix.Catalog.GetString ("Project A.P.E Cache"));
			this.typeEntry.AppendText (global::Mono.Unix.Catalog.GetString ("GPS Adventures Exhibit"));
			this.typeEntry.AppendText (global::Mono.Unix.Catalog.GetString ("Locationless Cache"));
			this.typeEntry.AppendText (global::Mono.Unix.Catalog.GetString ("Virtual Cache"));
			this.typeEntry.AppendText (global::Mono.Unix.Catalog.GetString ("Webcam Cache"));
			this.typeEntry.AppendText (global::Mono.Unix.Catalog.GetString ("Wherigo Cache"));
			this.typeEntry.AppendText (global::Mono.Unix.Catalog.GetString ("Cache In Trash Out Event"));
			this.typeEntry.AppendText (global::Mono.Unix.Catalog.GetString ("Mega Event Cache"));
			this.typeEntry.Name = "typeEntry";
			this.typeEntry.Active = 0;
			this.table2.Add (this.typeEntry);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table2 [this.typeEntry]));
			w20.TopAttach = ((uint)(1));
			w20.BottomAttach = ((uint)(2));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.urlEntry = new global::Gtk.Entry ();
			this.urlEntry.CanFocus = true;
			this.urlEntry.Name = "urlEntry";
			this.urlEntry.IsEditable = true;
			this.urlEntry.InvisibleChar = '•';
			this.table2.Add (this.urlEntry);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table2 [this.urlEntry]));
			w21.TopAttach = ((uint)(2));
			w21.BottomAttach = ((uint)(3));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.urlNameEntry = new global::Gtk.Entry ();
			this.urlNameEntry.CanFocus = true;
			this.urlNameEntry.Name = "urlNameEntry";
			this.urlNameEntry.IsEditable = true;
			this.urlNameEntry.InvisibleChar = '•';
			this.table2.Add (this.urlNameEntry);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table2 [this.urlNameEntry]));
			w22.TopAttach = ((uint)(3));
			w22.BottomAttach = ((uint)(4));
			w22.LeftAttach = ((uint)(1));
			w22.RightAttach = ((uint)(2));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook1.Add (this.table2);
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Waypoint Properties");
			this.notebook1.SetTabLabel (this.table2, this.label2);
			this.label2.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.table3 = new global::Gtk.Table (((uint)(6)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			this.table3.BorderWidth = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.diffEntry = global::Gtk.ComboBox.NewText ();
			this.diffEntry.AppendText (global::Mono.Unix.Catalog.GetString ("1"));
			this.diffEntry.AppendText (global::Mono.Unix.Catalog.GetString ("1.5"));
			this.diffEntry.AppendText (global::Mono.Unix.Catalog.GetString ("2"));
			this.diffEntry.AppendText (global::Mono.Unix.Catalog.GetString ("2.5"));
			this.diffEntry.AppendText (global::Mono.Unix.Catalog.GetString ("3"));
			this.diffEntry.AppendText (global::Mono.Unix.Catalog.GetString ("3.5"));
			this.diffEntry.AppendText (global::Mono.Unix.Catalog.GetString ("4"));
			this.diffEntry.AppendText (global::Mono.Unix.Catalog.GetString ("4.5"));
			this.diffEntry.AppendText (global::Mono.Unix.Catalog.GetString ("5"));
			this.diffEntry.Name = "diffEntry";
			this.diffEntry.Active = 0;
			this.table3.Add (this.diffEntry);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table3 [this.diffEntry]));
			w24.TopAttach = ((uint)(1));
			w24.BottomAttach = ((uint)(2));
			w24.LeftAttach = ((uint)(1));
			w24.RightAttach = ((uint)(2));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.frame5 = new global::Gtk.Frame ();
			this.frame5.Name = "frame5";
			this.frame5.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame5.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.shortDescEntry = new global::Gtk.TextView ();
			this.shortDescEntry.CanFocus = true;
			this.shortDescEntry.Name = "shortDescEntry";
			this.shortDescEntry.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow1.Add (this.shortDescEntry);
			this.GtkAlignment4.Add (this.GtkScrolledWindow1);
			this.frame5.Add (this.GtkAlignment4);
			this.GtkLabel4 = new global::Gtk.Label ();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Short Description</b>");
			this.GtkLabel4.UseMarkup = true;
			this.frame5.LabelWidget = this.GtkLabel4;
			this.table3.Add (this.frame5);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table3 [this.frame5]));
			w28.TopAttach = ((uint)(4));
			w28.BottomAttach = ((uint)(5));
			w28.RightAttach = ((uint)(2));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.frame6 = new global::Gtk.Frame ();
			this.frame6.Name = "frame6";
			this.frame6.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame6.Gtk.Container+ContainerChild
			this.GtkAlignment5 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment5.Name = "GtkAlignment5";
			this.GtkAlignment5.LeftPadding = ((uint)(12));
			// Container child GtkAlignment5.Gtk.Container+ContainerChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.longDescEntry = new global::Gtk.TextView ();
			this.longDescEntry.CanFocus = true;
			this.longDescEntry.Name = "longDescEntry";
			this.longDescEntry.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow2.Add (this.longDescEntry);
			this.GtkAlignment5.Add (this.GtkScrolledWindow2);
			this.frame6.Add (this.GtkAlignment5);
			this.GtkLabel5 = new global::Gtk.Label ();
			this.GtkLabel5.Name = "GtkLabel5";
			this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Long Description</b>");
			this.GtkLabel5.UseMarkup = true;
			this.frame6.LabelWidget = this.GtkLabel5;
			this.table3.Add (this.frame6);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table3 [this.frame6]));
			w32.TopAttach = ((uint)(5));
			w32.BottomAttach = ((uint)(6));
			w32.RightAttach = ((uint)(2));
			w32.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.frame7 = new global::Gtk.Frame ();
			this.frame7.Name = "frame7";
			this.frame7.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame7.Gtk.Container+ContainerChild
			this.GtkAlignment6 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment6.Name = "GtkAlignment6";
			this.GtkAlignment6.LeftPadding = ((uint)(12));
			// Container child GtkAlignment6.Gtk.Container+ContainerChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.hintEntry = new global::Gtk.TextView ();
			this.hintEntry.CanFocus = true;
			this.hintEntry.Name = "hintEntry";
			this.hintEntry.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow3.Add (this.hintEntry);
			this.GtkAlignment6.Add (this.GtkScrolledWindow3);
			this.frame7.Add (this.GtkAlignment6);
			this.GtkLabel6 = new global::Gtk.Label ();
			this.GtkLabel6.Name = "GtkLabel6";
			this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Hint</b>");
			this.GtkLabel6.UseMarkup = true;
			this.frame7.LabelWidget = this.GtkLabel6;
			this.table3.Add (this.frame7);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table3 [this.frame7]));
			w36.TopAttach = ((uint)(3));
			w36.BottomAttach = ((uint)(4));
			w36.RightAttach = ((uint)(2));
			w36.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.Xalign = 0F;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Cache Name:");
			this.table3.Add (this.label13);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table3 [this.label13]));
			w37.XOptions = ((global::Gtk.AttachOptions)(4));
			w37.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.Xalign = 0F;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Difficulty:");
			this.table3.Add (this.label14);
			global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table3 [this.label14]));
			w38.TopAttach = ((uint)(1));
			w38.BottomAttach = ((uint)(2));
			w38.XOptions = ((global::Gtk.AttachOptions)(4));
			w38.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.Xalign = 0F;
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Terrain:");
			this.table3.Add (this.label15);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table3 [this.label15]));
			w39.TopAttach = ((uint)(2));
			w39.BottomAttach = ((uint)(3));
			w39.XOptions = ((global::Gtk.AttachOptions)(4));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.nameEntry = new global::Gtk.Entry ();
			this.nameEntry.CanFocus = true;
			this.nameEntry.Name = "nameEntry";
			this.nameEntry.IsEditable = true;
			this.nameEntry.InvisibleChar = '•';
			this.table3.Add (this.nameEntry);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table3 [this.nameEntry]));
			w40.LeftAttach = ((uint)(1));
			w40.RightAttach = ((uint)(2));
			w40.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.terrEntry = global::Gtk.ComboBox.NewText ();
			this.terrEntry.AppendText (global::Mono.Unix.Catalog.GetString ("1"));
			this.terrEntry.AppendText (global::Mono.Unix.Catalog.GetString ("1.5"));
			this.terrEntry.AppendText (global::Mono.Unix.Catalog.GetString ("2"));
			this.terrEntry.AppendText (global::Mono.Unix.Catalog.GetString ("2.5"));
			this.terrEntry.AppendText (global::Mono.Unix.Catalog.GetString ("3"));
			this.terrEntry.AppendText (global::Mono.Unix.Catalog.GetString ("3.5"));
			this.terrEntry.AppendText (global::Mono.Unix.Catalog.GetString ("4"));
			this.terrEntry.AppendText (global::Mono.Unix.Catalog.GetString ("4.5"));
			this.terrEntry.AppendText (global::Mono.Unix.Catalog.GetString ("5"));
			this.terrEntry.Name = "terrEntry";
			this.terrEntry.Active = 0;
			this.table3.Add (this.terrEntry);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table3 [this.terrEntry]));
			w41.TopAttach = ((uint)(2));
			w41.BottomAttach = ((uint)(3));
			w41.LeftAttach = ((uint)(1));
			w41.RightAttach = ((uint)(2));
			w41.XOptions = ((global::Gtk.AttachOptions)(4));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook1.Add (this.table3);
			global::Gtk.Notebook.NotebookChild w42 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.table3]));
			w42.Position = 1;
			// Notebook tab
			this.name = new global::Gtk.Label ();
			this.name.Name = "name";
			this.name.LabelProp = global::Mono.Unix.Catalog.GetString ("Paperless Caching Details");
			this.notebook1.SetTabLabel (this.table3, this.name);
			this.name.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			this.vbox4.BorderWidth = ((uint)(6));
			// Container child vbox4.Gtk.Box+BoxChild
			this.frame8 = new global::Gtk.Frame ();
			this.frame8.Name = "frame8";
			this.frame8.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame8.Gtk.Container+ContainerChild
			this.GtkAlignment7 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment7.Name = "GtkAlignment7";
			this.GtkAlignment7.LeftPadding = ((uint)(12));
			// Container child GtkAlignment7.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(4)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.cacheIDEntry = new global::Gtk.Entry ();
			this.cacheIDEntry.CanFocus = true;
			this.cacheIDEntry.Name = "cacheIDEntry";
			this.cacheIDEntry.IsEditable = true;
			this.cacheIDEntry.InvisibleChar = '•';
			this.table1.Add (this.cacheIDEntry);
			global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table1 [this.cacheIDEntry]));
			w43.TopAttach = ((uint)(3));
			w43.BottomAttach = ((uint)(4));
			w43.LeftAttach = ((uint)(1));
			w43.RightAttach = ((uint)(2));
			w43.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.Xalign = 0F;
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Owner:");
			this.table1.Add (this.label19);
			global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table1 [this.label19]));
			w44.XOptions = ((global::Gtk.AttachOptions)(4));
			w44.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.Xalign = 0F;
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("Owner ID:");
			this.table1.Add (this.label20);
			global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table1 [this.label20]));
			w45.TopAttach = ((uint)(1));
			w45.BottomAttach = ((uint)(2));
			w45.XOptions = ((global::Gtk.AttachOptions)(4));
			w45.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label21 = new global::Gtk.Label ();
			this.label21.Name = "label21";
			this.label21.Xalign = 0F;
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("Placed By:");
			this.table1.Add (this.label21);
			global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table1 [this.label21]));
			w46.TopAttach = ((uint)(2));
			w46.BottomAttach = ((uint)(3));
			w46.XOptions = ((global::Gtk.AttachOptions)(4));
			w46.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label22 = new global::Gtk.Label ();
			this.label22.Name = "label22";
			this.label22.Xalign = 0F;
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("Cache ID:");
			this.table1.Add (this.label22);
			global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.table1 [this.label22]));
			w47.TopAttach = ((uint)(3));
			w47.BottomAttach = ((uint)(4));
			w47.XOptions = ((global::Gtk.AttachOptions)(4));
			w47.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ownerEntry = new global::Gtk.Entry ();
			this.ownerEntry.CanFocus = true;
			this.ownerEntry.Name = "ownerEntry";
			this.ownerEntry.IsEditable = true;
			this.ownerEntry.InvisibleChar = '•';
			this.table1.Add (this.ownerEntry);
			global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.table1 [this.ownerEntry]));
			w48.LeftAttach = ((uint)(1));
			w48.RightAttach = ((uint)(2));
			w48.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ownerIDEntry = new global::Gtk.Entry ();
			this.ownerIDEntry.CanFocus = true;
			this.ownerIDEntry.Name = "ownerIDEntry";
			this.ownerIDEntry.IsEditable = true;
			this.ownerIDEntry.InvisibleChar = '•';
			this.table1.Add (this.ownerIDEntry);
			global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.table1 [this.ownerIDEntry]));
			w49.TopAttach = ((uint)(1));
			w49.BottomAttach = ((uint)(2));
			w49.LeftAttach = ((uint)(1));
			w49.RightAttach = ((uint)(2));
			w49.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.placedByEntry = new global::Gtk.Entry ();
			this.placedByEntry.CanFocus = true;
			this.placedByEntry.Name = "placedByEntry";
			this.placedByEntry.IsEditable = true;
			this.placedByEntry.InvisibleChar = '•';
			this.table1.Add (this.placedByEntry);
			global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.table1 [this.placedByEntry]));
			w50.TopAttach = ((uint)(2));
			w50.BottomAttach = ((uint)(3));
			w50.LeftAttach = ((uint)(1));
			w50.RightAttach = ((uint)(2));
			w50.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment7.Add (this.table1);
			this.frame8.Add (this.GtkAlignment7);
			this.GtkLabel = new global::Gtk.Label ();
			this.GtkLabel.Name = "GtkLabel";
			this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Owner Details</b>");
			this.GtkLabel.UseMarkup = true;
			this.frame8.LabelWidget = this.GtkLabel;
			this.vbox4.Add (this.frame8);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.frame8]));
			w53.Position = 0;
			w53.Expand = false;
			w53.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.frame9 = new global::Gtk.Frame ();
			this.frame9.Name = "frame9";
			this.frame9.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame9.Gtk.Container+ContainerChild
			this.GtkAlignment8 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment8.Name = "GtkAlignment8";
			this.GtkAlignment8.LeftPadding = ((uint)(12));
			// Container child GtkAlignment8.Gtk.Container+ContainerChild
			this.table4 = new global::Gtk.Table (((uint)(4)), ((uint)(2)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.label23 = new global::Gtk.Label ();
			this.label23.Name = "label23";
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString ("User Data 2:");
			this.table4.Add (this.label23);
			global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.table4 [this.label23]));
			w54.TopAttach = ((uint)(1));
			w54.BottomAttach = ((uint)(2));
			w54.XOptions = ((global::Gtk.AttachOptions)(4));
			w54.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label24 = new global::Gtk.Label ();
			this.label24.Name = "label24";
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString ("User Data 3:");
			this.table4.Add (this.label24);
			global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.table4 [this.label24]));
			w55.TopAttach = ((uint)(2));
			w55.BottomAttach = ((uint)(3));
			w55.XOptions = ((global::Gtk.AttachOptions)(4));
			w55.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label25 = new global::Gtk.Label ();
			this.label25.Name = "label25";
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString ("User Data 4:");
			this.table4.Add (this.label25);
			global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.table4 [this.label25]));
			w56.TopAttach = ((uint)(3));
			w56.BottomAttach = ((uint)(4));
			w56.XOptions = ((global::Gtk.AttachOptions)(4));
			w56.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("User Data 1:");
			this.table4.Add (this.label5);
			global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.table4 [this.label5]));
			w57.XOptions = ((global::Gtk.AttachOptions)(4));
			w57.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.udata1Entry = new global::Gtk.Entry ();
			this.udata1Entry.CanFocus = true;
			this.udata1Entry.Name = "udata1Entry";
			this.udata1Entry.IsEditable = true;
			this.udata1Entry.InvisibleChar = '•';
			this.table4.Add (this.udata1Entry);
			global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.table4 [this.udata1Entry]));
			w58.LeftAttach = ((uint)(1));
			w58.RightAttach = ((uint)(2));
			w58.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.uData2Entry = new global::Gtk.Entry ();
			this.uData2Entry.CanFocus = true;
			this.uData2Entry.Name = "uData2Entry";
			this.uData2Entry.IsEditable = true;
			this.uData2Entry.InvisibleChar = '•';
			this.table4.Add (this.uData2Entry);
			global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.table4 [this.uData2Entry]));
			w59.TopAttach = ((uint)(1));
			w59.BottomAttach = ((uint)(2));
			w59.LeftAttach = ((uint)(1));
			w59.RightAttach = ((uint)(2));
			w59.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.uData3Entry = new global::Gtk.Entry ();
			this.uData3Entry.CanFocus = true;
			this.uData3Entry.Name = "uData3Entry";
			this.uData3Entry.IsEditable = true;
			this.uData3Entry.InvisibleChar = '•';
			this.table4.Add (this.uData3Entry);
			global::Gtk.Table.TableChild w60 = ((global::Gtk.Table.TableChild)(this.table4 [this.uData3Entry]));
			w60.TopAttach = ((uint)(2));
			w60.BottomAttach = ((uint)(3));
			w60.LeftAttach = ((uint)(1));
			w60.RightAttach = ((uint)(2));
			w60.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.uData4Entry = new global::Gtk.Entry ();
			this.uData4Entry.CanFocus = true;
			this.uData4Entry.Name = "uData4Entry";
			this.uData4Entry.IsEditable = true;
			this.uData4Entry.InvisibleChar = '•';
			this.table4.Add (this.uData4Entry);
			global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.table4 [this.uData4Entry]));
			w61.TopAttach = ((uint)(3));
			w61.BottomAttach = ((uint)(4));
			w61.LeftAttach = ((uint)(1));
			w61.RightAttach = ((uint)(2));
			w61.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment8.Add (this.table4);
			this.frame9.Add (this.GtkAlignment8);
			this.GtkLabel8 = new global::Gtk.Label ();
			this.GtkLabel8.Name = "GtkLabel8";
			this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>User Data</b>");
			this.GtkLabel8.UseMarkup = true;
			this.frame9.LabelWidget = this.GtkLabel8;
			this.vbox4.Add (this.frame9);
			global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.frame9]));
			w64.Position = 1;
			w64.Expand = false;
			w64.Fill = false;
			this.notebook1.Add (this.vbox4);
			global::Gtk.Notebook.NotebookChild w65 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox4]));
			w65.Position = 2;
			// Notebook tab
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Other Properties");
			this.notebook1.SetTabLabel (this.vbox4, this.label4);
			this.label4.ShowAll ();
			w1.Add (this.notebook1);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(w1 [this.notebook1]));
			w66.Position = 0;
			w66.Padding = ((uint)(6));
			// Internal child ocmgtk.ModifyCacheDialog.ActionArea
			global::Gtk.HButtonBox w67 = this.ActionArea;
			w67.Name = "dialog1_ActionArea";
			w67.Spacing = 10;
			w67.BorderWidth = ((uint)(5));
			w67.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w68 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w67 [this.buttonCancel]));
			w68.Expand = false;
			w68.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w69 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w67 [this.buttonOk]));
			w69.Position = 1;
			w69.Expand = false;
			w69.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 808;
			this.DefaultHeight = 577;
			this.Show ();
			this.corrButton.Clicked += new global::System.EventHandler (this.OnCorrClick);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnCancelClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
