
// This file has been generated by the GUI designer. Do not modify.
namespace ocmgtk
{
	public partial class OffLineLogViewer
	{
		private global::Gtk.VPaned vpaned1;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Image image11;
		
		private global::Gtk.Label fnFieldNotesLabel;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.ScrolledWindow scrolledwindow1;
		
		private global::Gtk.TreeView logView;
		
		private global::Gtk.VButtonBox vbuttonbox1;
		
		private global::Gtk.Button viewCacheButton;
		
		private global::Gtk.Button deleteButton;
		
		private global::Gtk.Button delAllButton;
		
		private global::Gtk.Notebook fieldNotesDescPane;
		
		private global::Gtk.VBox logPane;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.ComboBox logChoice;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.CheckButton firstToFindCheck;
		
		private global::Gtk.Button saveButton;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView logEntry;
		
		private global::Gtk.Label logPage;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label wptCombo;
		
		private global::Gtk.ComboBox waypointCombo;
		
		private global::ocmgtk.MapWidget mapView;
		
		private global::Gtk.Label label7;
		
		private global::ocmgtk.HTMLWidget cacheDesc;
		
		private global::Gtk.Label label5;
		
		private global::ocmgtk.HTMLWidget cacheLog;
		
		private global::Gtk.Label label8;
		
		private global::ocmgtk.NotesWidget cacheNotes;
		
		private global::Gtk.Label notesLabel;
		
		private global::Gtk.Button closeButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ocmgtk.OffLineLogViewer
			this.WidthRequest = 600;
			this.HeightRequest = 400;
			this.Name = "ocmgtk.OffLineLogViewer";
			this.Title = global::Mono.Unix.Catalog.GetString ("View Field Notes...");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.BorderWidth = ((uint)(6));
			this.AllowShrink = true;
			this.Gravity = ((global::Gdk.Gravity)(5));
			this.SkipPagerHint = true;
			this.SkipTaskbarHint = true;
			// Internal child ocmgtk.OffLineLogViewer.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.Spacing = 6;
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vpaned1 = new global::Gtk.VPaned ();
			this.vpaned1.CanFocus = true;
			this.vpaned1.Name = "vpaned1";
			this.vpaned1.Position = 250;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.image11 = new global::Gtk.Image ();
			this.image11.Name = "image11";
			this.image11.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-info", global::Gtk.IconSize.LargeToolbar);
			this.hbox1.Add (this.image11);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image11]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fnFieldNotesLabel = new global::Gtk.Label ();
			this.fnFieldNotesLabel.Name = "fnFieldNotesLabel";
			this.fnFieldNotesLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Please wait...");
			this.hbox1.Add (this.fnFieldNotesLabel);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.fnFieldNotesLabel]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox3.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox3.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hseparator1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.logView = new global::Gtk.TreeView ();
			this.logView.CanFocus = true;
			this.logView.Name = "logView";
			this.logView.EnableSearch = false;
			this.scrolledwindow1.Add (this.logView);
			this.hbox2.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.scrolledwindow1]));
			w7.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbuttonbox1 = new global::Gtk.VButtonBox ();
			this.vbuttonbox1.Name = "vbuttonbox1";
			this.vbuttonbox1.Spacing = 6;
			this.vbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.viewCacheButton = new global::Gtk.Button ();
			this.viewCacheButton.Sensitive = false;
			this.viewCacheButton.CanFocus = true;
			this.viewCacheButton.Name = "viewCacheButton";
			this.viewCacheButton.UseUnderline = true;
			this.viewCacheButton.Label = global::Mono.Unix.Catalog.GetString ("View Cache");
			this.vbuttonbox1.Add (this.viewCacheButton);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.viewCacheButton]));
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.deleteButton = new global::Gtk.Button ();
			this.deleteButton.Sensitive = false;
			this.deleteButton.CanFocus = true;
			this.deleteButton.Name = "deleteButton";
			this.deleteButton.UseStock = true;
			this.deleteButton.UseUnderline = true;
			this.deleteButton.Label = "gtk-delete";
			this.vbuttonbox1.Add (this.deleteButton);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.deleteButton]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.delAllButton = new global::Gtk.Button ();
			this.delAllButton.CanFocus = true;
			this.delAllButton.Name = "delAllButton";
			this.delAllButton.UseUnderline = true;
			this.delAllButton.Label = global::Mono.Unix.Catalog.GetString ("Delete All");
			this.vbuttonbox1.Add (this.delAllButton);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.delAllButton]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			this.hbox2.Add (this.vbuttonbox1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbuttonbox1]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			w11.Padding = ((uint)(6));
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w12.Position = 2;
			this.vpaned1.Add (this.vbox3);
			global::Gtk.Paned.PanedChild w13 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.vbox3]));
			w13.Resize = false;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.fieldNotesDescPane = new global::Gtk.Notebook ();
			this.fieldNotesDescPane.Sensitive = false;
			this.fieldNotesDescPane.CanFocus = true;
			this.fieldNotesDescPane.Name = "fieldNotesDescPane";
			this.fieldNotesDescPane.CurrentPage = 0;
			this.fieldNotesDescPane.TabPos = ((global::Gtk.PositionType)(0));
			// Container child fieldNotesDescPane.Gtk.Notebook+NotebookChild
			this.logPane = new global::Gtk.VBox ();
			this.logPane.Name = "logPane";
			this.logPane.Spacing = 6;
			this.logPane.BorderWidth = ((uint)(6));
			// Container child logPane.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Log Type:");
			this.hbox5.Add (this.label1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label1]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.logChoice = global::Gtk.ComboBox.NewText ();
			this.logChoice.AppendText (global::Mono.Unix.Catalog.GetString ("Found it"));
			this.logChoice.AppendText (global::Mono.Unix.Catalog.GetString ("Didn't Find it"));
			this.logChoice.AppendText (global::Mono.Unix.Catalog.GetString ("Write Note"));
			this.logChoice.AppendText (global::Mono.Unix.Catalog.GetString ("Needs Maintenance"));
			this.logChoice.Name = "logChoice";
			this.logChoice.Active = 0;
			this.hbox5.Add (this.logChoice);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.logChoice]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.logPane.Add (this.hbox5);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.logPane [this.hbox5]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child logPane.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.firstToFindCheck = new global::Gtk.CheckButton ();
			this.firstToFindCheck.CanFocus = true;
			this.firstToFindCheck.Name = "firstToFindCheck";
			this.firstToFindCheck.Label = global::Mono.Unix.Catalog.GetString ("First To Find");
			this.firstToFindCheck.DrawIndicator = true;
			this.firstToFindCheck.UseUnderline = true;
			this.hbox4.Add (this.firstToFindCheck);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.firstToFindCheck]));
			w17.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.saveButton = new global::Gtk.Button ();
			this.saveButton.CanFocus = true;
			this.saveButton.Name = "saveButton";
			this.saveButton.UseStock = true;
			this.saveButton.UseUnderline = true;
			this.saveButton.Label = "gtk-save";
			this.hbox4.Add (this.saveButton);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.saveButton]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.logPane.Add (this.hbox4);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.logPane [this.hbox4]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			// Container child logPane.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.logEntry = new global::Gtk.TextView ();
			this.logEntry.CanFocus = true;
			this.logEntry.Name = "logEntry";
			this.logEntry.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow.Add (this.logEntry);
			this.logPane.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.logPane [this.GtkScrolledWindow]));
			w21.Position = 2;
			this.fieldNotesDescPane.Add (this.logPane);
			// Notebook tab
			this.logPage = new global::Gtk.Label ();
			this.logPage.Name = "logPage";
			this.logPage.LabelProp = global::Mono.Unix.Catalog.GetString ("Field Log");
			this.fieldNotesDescPane.SetTabLabel (this.logPane, this.logPage);
			this.logPage.ShowAll ();
			// Container child fieldNotesDescPane.Gtk.Notebook+NotebookChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.wptCombo = new global::Gtk.Label ();
			this.wptCombo.Name = "wptCombo";
			this.wptCombo.LabelProp = global::Mono.Unix.Catalog.GetString ("Waypoint:");
			this.hbox3.Add (this.wptCombo);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.wptCombo]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.waypointCombo = global::Gtk.ComboBox.NewText ();
			this.waypointCombo.Name = "waypointCombo";
			this.hbox3.Add (this.waypointCombo);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.waypointCombo]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			this.vbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.mapView = null;
			this.vbox2.Add (this.mapView);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.mapView]));
			w26.Position = 1;
			this.fieldNotesDescPane.Add (this.vbox2);
			global::Gtk.Notebook.NotebookChild w27 = ((global::Gtk.Notebook.NotebookChild)(this.fieldNotesDescPane [this.vbox2]));
			w27.Position = 1;
			// Notebook tab
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Map");
			this.fieldNotesDescPane.SetTabLabel (this.vbox2, this.label7);
			this.label7.ShowAll ();
			// Container child fieldNotesDescPane.Gtk.Notebook+NotebookChild
			this.cacheDesc = new global::ocmgtk.HTMLWidget ();
			this.cacheDesc.Events = ((global::Gdk.EventMask)(256));
			this.cacheDesc.Name = "cacheDesc";
			this.fieldNotesDescPane.Add (this.cacheDesc);
			global::Gtk.Notebook.NotebookChild w28 = ((global::Gtk.Notebook.NotebookChild)(this.fieldNotesDescPane [this.cacheDesc]));
			w28.Position = 2;
			// Notebook tab
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Cache Description");
			this.fieldNotesDescPane.SetTabLabel (this.cacheDesc, this.label5);
			this.label5.ShowAll ();
			// Container child fieldNotesDescPane.Gtk.Notebook+NotebookChild
			this.cacheLog = new global::ocmgtk.HTMLWidget ();
			this.cacheLog.Events = ((global::Gdk.EventMask)(256));
			this.cacheLog.Name = "cacheLog";
			this.fieldNotesDescPane.Add (this.cacheLog);
			global::Gtk.Notebook.NotebookChild w29 = ((global::Gtk.Notebook.NotebookChild)(this.fieldNotesDescPane [this.cacheLog]));
			w29.Position = 3;
			// Notebook tab
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Cache Logs");
			this.fieldNotesDescPane.SetTabLabel (this.cacheLog, this.label8);
			this.label8.ShowAll ();
			// Container child fieldNotesDescPane.Gtk.Notebook+NotebookChild
			this.cacheNotes = null;
			this.fieldNotesDescPane.Add (this.cacheNotes);
			global::Gtk.Notebook.NotebookChild w30 = ((global::Gtk.Notebook.NotebookChild)(this.fieldNotesDescPane [this.cacheNotes]));
			w30.Position = 4;
			// Notebook tab
			this.notesLabel = new global::Gtk.Label ();
			this.notesLabel.Name = "notesLabel";
			this.notesLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Notes");
			this.fieldNotesDescPane.SetTabLabel (this.cacheNotes, this.notesLabel);
			this.notesLabel.ShowAll ();
			this.vpaned1.Add (this.fieldNotesDescPane);
			w1.Add (this.vpaned1);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(w1 [this.vpaned1]));
			w32.Position = 0;
			// Internal child ocmgtk.OffLineLogViewer.ActionArea
			global::Gtk.HButtonBox w33 = this.ActionArea;
			w33.Name = "dialog1_ActionArea";
			w33.Spacing = 10;
			w33.BorderWidth = ((uint)(5));
			w33.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.closeButton = new global::Gtk.Button ();
			this.closeButton.CanDefault = true;
			this.closeButton.CanFocus = true;
			this.closeButton.Name = "closeButton";
			this.closeButton.UseStock = true;
			this.closeButton.UseUnderline = true;
			this.closeButton.Label = "gtk-close";
			this.AddActionWidget (this.closeButton, -7);
			global::Gtk.ButtonBox.ButtonBoxChild w34 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w33 [this.closeButton]));
			w34.Expand = false;
			w34.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 839;
			this.DefaultHeight = 566;
			this.closeButton.HasDefault = true;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnCloseClick);
			this.viewCacheButton.Clicked += new global::System.EventHandler (this.OnViewCache);
			this.deleteButton.Clicked += new global::System.EventHandler (this.OnDeleteClick);
			this.delAllButton.Clicked += new global::System.EventHandler (this.OnDeleteAllClick);
			this.logChoice.Changed += new global::System.EventHandler (this.OnLogTypeChange);
			this.firstToFindCheck.Toggled += new global::System.EventHandler (this.OnFTFCheck);
			this.saveButton.Clicked += new global::System.EventHandler (this.OnSaveClick);
			this.closeButton.Clicked += new global::System.EventHandler (this.OnCloseClick);
		}
	}
}
