
// This file has been generated by the GUI designer. Do not modify.
namespace ocmgtk
{
	public partial class GeoCachePane
	{
		private global::Gtk.Alignment alignment1;
		
		private global::Gtk.Notebook notebook2;
		
		private global::ocmgtk.GeocacheInfoPanel cacheInfo;
		
		private global::Gtk.Label label12;
		
		private global::ocmgtk.DescriptionWidget descWidget;
		
		private global::Gtk.Label label13;
		
		private global::ocmgtk.LogViewerWidget logView;
		
		private global::Gtk.Label label14;
		
		private global::ocmgtk.WaypointWidget waypointView;
		
		private global::Gtk.Label label15;
		
		private global::ocmgtk.NotesWidget notesWidget;
		
		private global::Gtk.Label label16;
		
		private global::ocmgtk.ImagesWidget cacheImages;
		
		private global::Gtk.Label label17;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ocmgtk.GeoCachePane
			global::Stetic.BinContainer.Attach (this);
			this.Name = "ocmgtk.GeoCachePane";
			// Container child ocmgtk.GeoCachePane.Gtk.Container+ContainerChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			// Container child alignment1.Gtk.Container+ContainerChild
			this.notebook2 = new global::Gtk.Notebook ();
			this.notebook2.CanFocus = true;
			this.notebook2.Name = "notebook2";
			this.notebook2.CurrentPage = 5;
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.cacheInfo = null;
			this.notebook2.Add (this.cacheInfo);
			// Notebook tab
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Quick Info");
			this.notebook2.SetTabLabel (this.cacheInfo, this.label12);
			this.label12.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.descWidget = null;
			this.notebook2.Add (this.descWidget);
			global::Gtk.Notebook.NotebookChild w2 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.descWidget]));
			w2.Position = 1;
			// Notebook tab
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Description");
			this.notebook2.SetTabLabel (this.descWidget, this.label13);
			this.label13.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.logView = null;
			this.notebook2.Add (this.logView);
			global::Gtk.Notebook.NotebookChild w3 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.logView]));
			w3.Position = 2;
			// Notebook tab
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Logs");
			this.notebook2.SetTabLabel (this.logView, this.label14);
			this.label14.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.waypointView = null;
			this.notebook2.Add (this.waypointView);
			global::Gtk.Notebook.NotebookChild w4 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.waypointView]));
			w4.Position = 3;
			// Notebook tab
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Waypoints");
			this.notebook2.SetTabLabel (this.waypointView, this.label15);
			this.label15.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.notesWidget = null;
			this.notebook2.Add (this.notesWidget);
			global::Gtk.Notebook.NotebookChild w5 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.notesWidget]));
			w5.Position = 4;
			// Notebook tab
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Notes");
			this.notebook2.SetTabLabel (this.notesWidget, this.label16);
			this.label16.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.cacheImages = null;
			this.notebook2.Add (this.cacheImages);
			global::Gtk.Notebook.NotebookChild w6 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.cacheImages]));
			w6.Position = 5;
			// Notebook tab
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Images");
			this.notebook2.SetTabLabel (this.cacheImages, this.label17);
			this.label17.ShowAll ();
			this.alignment1.Add (this.notebook2);
			this.Add (this.alignment1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
