
// This file has been generated by the GUI designer. Do not modify.
namespace ocmgtk
{
	public partial class SymbolChooser
	{
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label symbolLabel;
		
		private global::Gtk.ComboBoxEntry symbolCombo;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ocmgtk.SymbolChooser
			global::Stetic.BinContainer.Attach (this);
			this.Name = "ocmgtk.SymbolChooser";
			// Container child ocmgtk.SymbolChooser.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.symbolLabel = new global::Gtk.Label ();
			this.symbolLabel.Name = "symbolLabel";
			this.symbolLabel.Xalign = 0F;
			this.symbolLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("label4");
			this.symbolLabel.WidthChars = 30;
			this.hbox1.Add (this.symbolLabel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.symbolLabel]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.symbolCombo = global::Gtk.ComboBoxEntry.NewText ();
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Geocache"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Geocache Found"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Flag, Red"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Flag, Blue"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Flag, Green"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Pin, Red"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Pin, Blue"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Pin, Green"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Block, Red"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Block, Blue"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Block, Green"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Custom 0"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Custom 1"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Custom 2"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Custom 3"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Custom 4"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Custom 5"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Custom 6"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Custom 7"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Custom 8"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Custom 9"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Custom 10"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Custom 11"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Custom 12"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Custom 13"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Custom 14"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Custom 15"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Custom 16"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Custom 17"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Custom 18"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Custom 19"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Custom 20"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Custom 21"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Custom 22"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Custom 23"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Custom 24"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Anchor"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Bell"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Diver Down Flag 1"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Diver Down Flag 2"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Bank"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Fishing Area"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Gas Station"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Horn"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Residence"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Restaurant"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Light"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Bar"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Skull and Crossbones"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Buoy, White"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Shipwreck"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Man Overboard"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Navaid, Amber"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Navaid, Black"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Navaid, Blue"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Navaid, Green"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Navaid, Orange"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Navaid, Red"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Navaid, Violet"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Navaid, White"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Radio Beacon"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Boat Ramp"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Campground"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Restroom"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Shower"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Drinking Water"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Telephone"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Medical Facility"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Information"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Parking Area"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Park"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Picnic Area"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Scenic Area"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Skiing Area"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Swimming Area"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Dam"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Controlled Area"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Danger Area"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Restricted Area"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Ball Park"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Car"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Shopping Center"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Lodging"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Mine"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Trail Head"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Truck Stop"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Golf Course"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("City (Small)"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("City (Medium)"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("City (Large)"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Amusement Park"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Bowling"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Car Rental"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Car Repair"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Fast Food"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Fitness Center"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Movie Theater"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Museum"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Pharmacy"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Pizza"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Post Office"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("RV Park"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("School"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Stadium"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Department Store"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Zoo"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Convenience Store"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Live Theater"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Scales"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Toll Booth"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Bridge"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Building"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Cemetery"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Church"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Civil"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Crossing"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Oil Field"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Tunnel"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Beach"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Forest"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Summit"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Airport"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Tall Tower"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Short Tower"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Glider Area"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Ultralight Area"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Parachute Area"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Bike Trail"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Fishing Hot Spot Facility"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Police Station"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Ski Resort"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Ice Skating"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Wrecker"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("ATV"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Big Game"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Blind"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Blood Trail"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Cover"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Covey"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Food Source"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Furbearer"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Lodge"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Small Game"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Animal Tracks"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Treed Quarry"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Tree Stand"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Truck"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Upland Game"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Waterfowl"));
			this.symbolCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Water Source"));
			this.symbolCombo.Name = "symbolCombo";
			this.hbox1.Add (this.symbolCombo);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.symbolCombo]));
			w2.Position = 1;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
