// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ocmgtk {
    
    
    public partial class OCMQueryPage1 {
        
        private Gtk.VBox vbox1;
        
        private Gtk.Frame frame1;
        
        private Gtk.Alignment GtkAlignment1;
        
        private Gtk.Table table1;
        
        private Gtk.CheckButton diffCheck;
        
        private Gtk.ComboBox diffRange;
        
        private Gtk.ComboBox diffValue;
        
        private Gtk.CheckButton terrainCheck;
        
        private Gtk.ComboBox terrRange;
        
        private Gtk.ComboBox terrValue;
        
        private Gtk.Label GtkLabel19;
        
        private Gtk.Frame frame2;
        
        private Gtk.Alignment GtkAlignment2;
        
        private Gtk.VBox vbox2;
        
        private Gtk.RadioButton allCacheRadio;
        
        private Gtk.RadioButton selCacheRadio;
        
        private Gtk.Frame selCacheFrame;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.Table table2;
        
        private Gtk.CheckButton advCheck;
        
        private Gtk.CheckButton apeCheck;
        
        private Gtk.CheckButton citoCheck;
        
        private Gtk.CheckButton earCheck;
        
        private Gtk.CheckButton evntCheck;
        
        private Gtk.CheckButton lettCheck;
        
        private Gtk.CheckButton locCheck;
        
        private Gtk.CheckButton megaCheck;
        
        private Gtk.CheckButton multiCheck;
        
        private Gtk.CheckButton tradCheck;
        
        private Gtk.CheckButton unkCheck;
        
        private Gtk.CheckButton virtCheck;
        
        private Gtk.CheckButton webCheck;
        
        private Gtk.CheckButton wherigoCheck;
        
        private Gtk.CheckButton providerCheck;
        
        private Gtk.Frame sourceFrame;
        
        private Gtk.Alignment GtkAlignment3;
        
        private Gtk.Table table3;
        
        private Gtk.CheckButton gcComCheck;
        
        private Gtk.CheckButton NaviCacheCheck;
        
        private Gtk.CheckButton openCacheCheck;
        
        private Gtk.CheckButton terraCachingCheck;
        
        private Gtk.CheckButton wayMarkingCheck;
        
        private Gtk.Label GtkLabel25;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ocmgtk.OCMQueryPage1
            Stetic.BinContainer.Attach(this);
            this.Name = "ocmgtk.OCMQueryPage1";
            // Container child ocmgtk.OCMQueryPage1.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            this.vbox1.BorderWidth = ((uint)(6));
            // Container child vbox1.Gtk.Box+BoxChild
            this.frame1 = new Gtk.Frame();
            this.frame1.Name = "frame1";
            this.frame1.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame1.Gtk.Container+ContainerChild
            this.GtkAlignment1 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment1.Name = "GtkAlignment1";
            this.GtkAlignment1.LeftPadding = ((uint)(12));
            // Container child GtkAlignment1.Gtk.Container+ContainerChild
            this.table1 = new Gtk.Table(((uint)(2)), ((uint)(3)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            this.table1.BorderWidth = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.diffCheck = new Gtk.CheckButton();
            this.diffCheck.CanFocus = true;
            this.diffCheck.Name = "diffCheck";
            this.diffCheck.Label = Mono.Unix.Catalog.GetString("Difficulty");
            this.diffCheck.DrawIndicator = true;
            this.diffCheck.UseUnderline = true;
            this.table1.Add(this.diffCheck);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table1[this.diffCheck]));
            w1.XOptions = ((Gtk.AttachOptions)(4));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.diffRange = Gtk.ComboBox.NewText();
            this.diffRange.AppendText(Mono.Unix.Catalog.GetString("Greater Than"));
            this.diffRange.AppendText(Mono.Unix.Catalog.GetString("Greater Than or Equal To"));
            this.diffRange.AppendText(Mono.Unix.Catalog.GetString("Equal To"));
            this.diffRange.AppendText(Mono.Unix.Catalog.GetString("Less Than or Equal To"));
            this.diffRange.AppendText(Mono.Unix.Catalog.GetString("Less Than"));
            this.diffRange.Sensitive = false;
            this.diffRange.Name = "diffRange";
            this.diffRange.Active = 0;
            this.table1.Add(this.diffRange);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.diffRange]));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(2));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.diffValue = Gtk.ComboBox.NewText();
            this.diffValue.AppendText(Mono.Unix.Catalog.GetString("1"));
            this.diffValue.AppendText(Mono.Unix.Catalog.GetString("1.5"));
            this.diffValue.AppendText(Mono.Unix.Catalog.GetString("2"));
            this.diffValue.AppendText(Mono.Unix.Catalog.GetString("2.5"));
            this.diffValue.AppendText(Mono.Unix.Catalog.GetString("3"));
            this.diffValue.AppendText(Mono.Unix.Catalog.GetString("3.5"));
            this.diffValue.AppendText(Mono.Unix.Catalog.GetString("4"));
            this.diffValue.AppendText(Mono.Unix.Catalog.GetString("4.5"));
            this.diffValue.AppendText(Mono.Unix.Catalog.GetString("5"));
            this.diffValue.Sensitive = false;
            this.diffValue.Name = "diffValue";
            this.diffValue.Active = 0;
            this.table1.Add(this.diffValue);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.diffValue]));
            w3.LeftAttach = ((uint)(2));
            w3.RightAttach = ((uint)(3));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.terrainCheck = new Gtk.CheckButton();
            this.terrainCheck.CanFocus = true;
            this.terrainCheck.Name = "terrainCheck";
            this.terrainCheck.Label = Mono.Unix.Catalog.GetString("Terrain");
            this.terrainCheck.DrawIndicator = true;
            this.terrainCheck.UseUnderline = true;
            this.table1.Add(this.terrainCheck);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.terrainCheck]));
            w4.TopAttach = ((uint)(1));
            w4.BottomAttach = ((uint)(2));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.terrRange = Gtk.ComboBox.NewText();
            this.terrRange.AppendText(Mono.Unix.Catalog.GetString("Greater Than"));
            this.terrRange.AppendText(Mono.Unix.Catalog.GetString("Greater Than or Equal To"));
            this.terrRange.AppendText(Mono.Unix.Catalog.GetString("Equal To"));
            this.terrRange.AppendText(Mono.Unix.Catalog.GetString("Less Than or Equal To"));
            this.terrRange.AppendText(Mono.Unix.Catalog.GetString("Less Than"));
            this.terrRange.Sensitive = false;
            this.terrRange.Name = "terrRange";
            this.terrRange.Active = 0;
            this.table1.Add(this.terrRange);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.terrRange]));
            w5.TopAttach = ((uint)(1));
            w5.BottomAttach = ((uint)(2));
            w5.LeftAttach = ((uint)(1));
            w5.RightAttach = ((uint)(2));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.terrValue = Gtk.ComboBox.NewText();
            this.terrValue.AppendText(Mono.Unix.Catalog.GetString("1"));
            this.terrValue.AppendText(Mono.Unix.Catalog.GetString("1.5"));
            this.terrValue.AppendText(Mono.Unix.Catalog.GetString("2"));
            this.terrValue.AppendText(Mono.Unix.Catalog.GetString("2.5"));
            this.terrValue.AppendText(Mono.Unix.Catalog.GetString("3"));
            this.terrValue.AppendText(Mono.Unix.Catalog.GetString("3.5"));
            this.terrValue.AppendText(Mono.Unix.Catalog.GetString("4"));
            this.terrValue.AppendText(Mono.Unix.Catalog.GetString("4.5"));
            this.terrValue.AppendText(Mono.Unix.Catalog.GetString("5"));
            this.terrValue.Sensitive = false;
            this.terrValue.Name = "terrValue";
            this.terrValue.Active = 0;
            this.table1.Add(this.terrValue);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table1[this.terrValue]));
            w6.TopAttach = ((uint)(1));
            w6.BottomAttach = ((uint)(2));
            w6.LeftAttach = ((uint)(2));
            w6.RightAttach = ((uint)(3));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment1.Add(this.table1);
            this.frame1.Add(this.GtkAlignment1);
            this.GtkLabel19 = new Gtk.Label();
            this.GtkLabel19.Name = "GtkLabel19";
            this.GtkLabel19.LabelProp = Mono.Unix.Catalog.GetString("<b>Difficulty &amp; Terrain</b>");
            this.GtkLabel19.UseMarkup = true;
            this.frame1.LabelWidget = this.GtkLabel19;
            this.vbox1.Add(this.frame1);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox1[this.frame1]));
            w9.Position = 0;
            w9.Expand = false;
            w9.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.frame2 = new Gtk.Frame();
            this.frame2.Name = "frame2";
            this.frame2.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame2.Gtk.Container+ContainerChild
            this.GtkAlignment2 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment2.Name = "GtkAlignment2";
            this.GtkAlignment2.LeftPadding = ((uint)(12));
            // Container child GtkAlignment2.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.allCacheRadio = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("Any cache type"));
            this.allCacheRadio.CanFocus = true;
            this.allCacheRadio.Name = "allCacheRadio";
            this.allCacheRadio.Active = true;
            this.allCacheRadio.DrawIndicator = true;
            this.allCacheRadio.UseUnderline = true;
            this.allCacheRadio.Group = new GLib.SList(System.IntPtr.Zero);
            this.vbox2.Add(this.allCacheRadio);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox2[this.allCacheRadio]));
            w10.Position = 0;
            w10.Expand = false;
            w10.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.selCacheRadio = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("Any of the following types:"));
            this.selCacheRadio.CanFocus = true;
            this.selCacheRadio.Name = "selCacheRadio";
            this.selCacheRadio.DrawIndicator = true;
            this.selCacheRadio.UseUnderline = true;
            this.selCacheRadio.Group = this.allCacheRadio.Group;
            this.vbox2.Add(this.selCacheRadio);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.vbox2[this.selCacheRadio]));
            w11.Position = 1;
            w11.Expand = false;
            w11.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.selCacheFrame = new Gtk.Frame();
            this.selCacheFrame.Sensitive = false;
            this.selCacheFrame.Name = "selCacheFrame";
            this.selCacheFrame.ShadowType = ((Gtk.ShadowType)(1));
            // Container child selCacheFrame.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.table2 = new Gtk.Table(((uint)(5)), ((uint)(3)), false);
            this.table2.Name = "table2";
            this.table2.RowSpacing = ((uint)(6));
            this.table2.ColumnSpacing = ((uint)(6));
            this.table2.BorderWidth = ((uint)(6));
            // Container child table2.Gtk.Table+TableChild
            this.advCheck = new Gtk.CheckButton();
            this.advCheck.CanFocus = true;
            this.advCheck.Name = "advCheck";
            this.advCheck.Label = Mono.Unix.Catalog.GetString("Adventure Maze");
            this.advCheck.DrawIndicator = true;
            this.advCheck.UseUnderline = true;
            this.table2.Add(this.advCheck);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table2[this.advCheck]));
            w12.TopAttach = ((uint)(3));
            w12.BottomAttach = ((uint)(4));
            w12.LeftAttach = ((uint)(1));
            w12.RightAttach = ((uint)(2));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.apeCheck = new Gtk.CheckButton();
            this.apeCheck.CanFocus = true;
            this.apeCheck.Name = "apeCheck";
            this.apeCheck.Label = Mono.Unix.Catalog.GetString("A.P.E.");
            this.apeCheck.DrawIndicator = true;
            this.apeCheck.UseUnderline = true;
            this.table2.Add(this.apeCheck);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table2[this.apeCheck]));
            w13.TopAttach = ((uint)(4));
            w13.BottomAttach = ((uint)(5));
            w13.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.citoCheck = new Gtk.CheckButton();
            this.citoCheck.CanFocus = true;
            this.citoCheck.Name = "citoCheck";
            this.citoCheck.Label = Mono.Unix.Catalog.GetString("CITO");
            this.citoCheck.DrawIndicator = true;
            this.citoCheck.UseUnderline = true;
            this.table2.Add(this.citoCheck);
            Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table2[this.citoCheck]));
            w14.TopAttach = ((uint)(2));
            w14.BottomAttach = ((uint)(3));
            w14.LeftAttach = ((uint)(2));
            w14.RightAttach = ((uint)(3));
            w14.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.earCheck = new Gtk.CheckButton();
            this.earCheck.CanFocus = true;
            this.earCheck.Name = "earCheck";
            this.earCheck.Label = Mono.Unix.Catalog.GetString("Earth Cache");
            this.earCheck.DrawIndicator = true;
            this.earCheck.UseUnderline = true;
            this.table2.Add(this.earCheck);
            Gtk.Table.TableChild w15 = ((Gtk.Table.TableChild)(this.table2[this.earCheck]));
            w15.TopAttach = ((uint)(2));
            w15.BottomAttach = ((uint)(3));
            w15.LeftAttach = ((uint)(1));
            w15.RightAttach = ((uint)(2));
            w15.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.evntCheck = new Gtk.CheckButton();
            this.evntCheck.CanFocus = true;
            this.evntCheck.Name = "evntCheck";
            this.evntCheck.Label = Mono.Unix.Catalog.GetString("Event Cache");
            this.evntCheck.DrawIndicator = true;
            this.evntCheck.UseUnderline = true;
            this.table2.Add(this.evntCheck);
            Gtk.Table.TableChild w16 = ((Gtk.Table.TableChild)(this.table2[this.evntCheck]));
            w16.LeftAttach = ((uint)(2));
            w16.RightAttach = ((uint)(3));
            w16.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.lettCheck = new Gtk.CheckButton();
            this.lettCheck.CanFocus = true;
            this.lettCheck.Name = "lettCheck";
            this.lettCheck.Label = Mono.Unix.Catalog.GetString("Letterbox Hybrid");
            this.lettCheck.DrawIndicator = true;
            this.lettCheck.UseUnderline = true;
            this.table2.Add(this.lettCheck);
            Gtk.Table.TableChild w17 = ((Gtk.Table.TableChild)(this.table2[this.lettCheck]));
            w17.LeftAttach = ((uint)(1));
            w17.RightAttach = ((uint)(2));
            w17.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.locCheck = new Gtk.CheckButton();
            this.locCheck.CanFocus = true;
            this.locCheck.Name = "locCheck";
            this.locCheck.Label = Mono.Unix.Catalog.GetString("Locationless");
            this.locCheck.DrawIndicator = true;
            this.locCheck.UseUnderline = true;
            this.table2.Add(this.locCheck);
            Gtk.Table.TableChild w18 = ((Gtk.Table.TableChild)(this.table2[this.locCheck]));
            w18.TopAttach = ((uint)(4));
            w18.BottomAttach = ((uint)(5));
            w18.LeftAttach = ((uint)(1));
            w18.RightAttach = ((uint)(2));
            w18.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.megaCheck = new Gtk.CheckButton();
            this.megaCheck.CanFocus = true;
            this.megaCheck.Name = "megaCheck";
            this.megaCheck.Label = Mono.Unix.Catalog.GetString("Mega Event");
            this.megaCheck.DrawIndicator = true;
            this.megaCheck.UseUnderline = true;
            this.table2.Add(this.megaCheck);
            Gtk.Table.TableChild w19 = ((Gtk.Table.TableChild)(this.table2[this.megaCheck]));
            w19.TopAttach = ((uint)(1));
            w19.BottomAttach = ((uint)(2));
            w19.LeftAttach = ((uint)(2));
            w19.RightAttach = ((uint)(3));
            w19.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.multiCheck = new Gtk.CheckButton();
            this.multiCheck.CanFocus = true;
            this.multiCheck.Name = "multiCheck";
            this.multiCheck.Label = Mono.Unix.Catalog.GetString("Multi-Cache");
            this.multiCheck.DrawIndicator = true;
            this.multiCheck.UseUnderline = true;
            this.table2.Add(this.multiCheck);
            Gtk.Table.TableChild w20 = ((Gtk.Table.TableChild)(this.table2[this.multiCheck]));
            w20.TopAttach = ((uint)(1));
            w20.BottomAttach = ((uint)(2));
            w20.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.tradCheck = new Gtk.CheckButton();
            this.tradCheck.CanFocus = true;
            this.tradCheck.Name = "tradCheck";
            this.tradCheck.Label = Mono.Unix.Catalog.GetString("Traditional");
            this.tradCheck.DrawIndicator = true;
            this.tradCheck.UseUnderline = true;
            this.table2.Add(this.tradCheck);
            Gtk.Table.TableChild w21 = ((Gtk.Table.TableChild)(this.table2[this.tradCheck]));
            w21.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.unkCheck = new Gtk.CheckButton();
            this.unkCheck.CanFocus = true;
            this.unkCheck.Name = "unkCheck";
            this.unkCheck.Label = Mono.Unix.Catalog.GetString("Unknown");
            this.unkCheck.DrawIndicator = true;
            this.unkCheck.UseUnderline = true;
            this.table2.Add(this.unkCheck);
            Gtk.Table.TableChild w22 = ((Gtk.Table.TableChild)(this.table2[this.unkCheck]));
            w22.TopAttach = ((uint)(2));
            w22.BottomAttach = ((uint)(3));
            w22.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.virtCheck = new Gtk.CheckButton();
            this.virtCheck.CanFocus = true;
            this.virtCheck.Name = "virtCheck";
            this.virtCheck.Label = Mono.Unix.Catalog.GetString("Virtual");
            this.virtCheck.DrawIndicator = true;
            this.virtCheck.UseUnderline = true;
            this.table2.Add(this.virtCheck);
            Gtk.Table.TableChild w23 = ((Gtk.Table.TableChild)(this.table2[this.virtCheck]));
            w23.TopAttach = ((uint)(3));
            w23.BottomAttach = ((uint)(4));
            w23.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.webCheck = new Gtk.CheckButton();
            this.webCheck.CanFocus = true;
            this.webCheck.Name = "webCheck";
            this.webCheck.Label = Mono.Unix.Catalog.GetString("Webcam");
            this.webCheck.DrawIndicator = true;
            this.webCheck.UseUnderline = true;
            this.table2.Add(this.webCheck);
            Gtk.Table.TableChild w24 = ((Gtk.Table.TableChild)(this.table2[this.webCheck]));
            w24.TopAttach = ((uint)(3));
            w24.BottomAttach = ((uint)(4));
            w24.LeftAttach = ((uint)(2));
            w24.RightAttach = ((uint)(3));
            w24.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.wherigoCheck = new Gtk.CheckButton();
            this.wherigoCheck.CanFocus = true;
            this.wherigoCheck.Name = "wherigoCheck";
            this.wherigoCheck.Label = Mono.Unix.Catalog.GetString("Wherigo");
            this.wherigoCheck.DrawIndicator = true;
            this.wherigoCheck.UseUnderline = true;
            this.table2.Add(this.wherigoCheck);
            Gtk.Table.TableChild w25 = ((Gtk.Table.TableChild)(this.table2[this.wherigoCheck]));
            w25.TopAttach = ((uint)(1));
            w25.BottomAttach = ((uint)(2));
            w25.LeftAttach = ((uint)(1));
            w25.RightAttach = ((uint)(2));
            w25.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment.Add(this.table2);
            this.selCacheFrame.Add(this.GtkAlignment);
            this.vbox2.Add(this.selCacheFrame);
            Gtk.Box.BoxChild w28 = ((Gtk.Box.BoxChild)(this.vbox2[this.selCacheFrame]));
            w28.Position = 2;
            w28.Expand = false;
            w28.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.providerCheck = new Gtk.CheckButton();
            this.providerCheck.CanFocus = true;
            this.providerCheck.Name = "providerCheck";
            this.providerCheck.Label = Mono.Unix.Catalog.GetString("Cache Source:");
            this.providerCheck.DrawIndicator = true;
            this.providerCheck.UseUnderline = true;
            this.vbox2.Add(this.providerCheck);
            Gtk.Box.BoxChild w29 = ((Gtk.Box.BoxChild)(this.vbox2[this.providerCheck]));
            w29.Position = 3;
            w29.Expand = false;
            w29.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.sourceFrame = new Gtk.Frame();
            this.sourceFrame.Sensitive = false;
            this.sourceFrame.Name = "sourceFrame";
            this.sourceFrame.ShadowType = ((Gtk.ShadowType)(1));
            // Container child sourceFrame.Gtk.Container+ContainerChild
            this.GtkAlignment3 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment3.Name = "GtkAlignment3";
            this.GtkAlignment3.LeftPadding = ((uint)(12));
            // Container child GtkAlignment3.Gtk.Container+ContainerChild
            this.table3 = new Gtk.Table(((uint)(2)), ((uint)(3)), false);
            this.table3.Name = "table3";
            this.table3.RowSpacing = ((uint)(6));
            this.table3.ColumnSpacing = ((uint)(6));
            // Container child table3.Gtk.Table+TableChild
            this.gcComCheck = new Gtk.CheckButton();
            this.gcComCheck.CanFocus = true;
            this.gcComCheck.Name = "gcComCheck";
            this.gcComCheck.Label = Mono.Unix.Catalog.GetString("Geocaching.com");
            this.gcComCheck.DrawIndicator = true;
            this.gcComCheck.UseUnderline = true;
            this.table3.Add(this.gcComCheck);
            Gtk.Table.TableChild w30 = ((Gtk.Table.TableChild)(this.table3[this.gcComCheck]));
            w30.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.NaviCacheCheck = new Gtk.CheckButton();
            this.NaviCacheCheck.CanFocus = true;
            this.NaviCacheCheck.Name = "NaviCacheCheck";
            this.NaviCacheCheck.Label = Mono.Unix.Catalog.GetString("NaviCache");
            this.NaviCacheCheck.DrawIndicator = true;
            this.NaviCacheCheck.UseUnderline = true;
            this.table3.Add(this.NaviCacheCheck);
            Gtk.Table.TableChild w31 = ((Gtk.Table.TableChild)(this.table3[this.NaviCacheCheck]));
            w31.LeftAttach = ((uint)(2));
            w31.RightAttach = ((uint)(3));
            w31.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.openCacheCheck = new Gtk.CheckButton();
            this.openCacheCheck.CanFocus = true;
            this.openCacheCheck.Name = "openCacheCheck";
            this.openCacheCheck.Label = Mono.Unix.Catalog.GetString("OpenCaching (.eu/.us/.jp)");
            this.openCacheCheck.DrawIndicator = true;
            this.openCacheCheck.UseUnderline = true;
            this.table3.Add(this.openCacheCheck);
            Gtk.Table.TableChild w32 = ((Gtk.Table.TableChild)(this.table3[this.openCacheCheck]));
            w32.LeftAttach = ((uint)(1));
            w32.RightAttach = ((uint)(2));
            w32.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.terraCachingCheck = new Gtk.CheckButton();
            this.terraCachingCheck.CanFocus = true;
            this.terraCachingCheck.Name = "terraCachingCheck";
            this.terraCachingCheck.Label = Mono.Unix.Catalog.GetString("Terracaching.com");
            this.terraCachingCheck.DrawIndicator = true;
            this.terraCachingCheck.UseUnderline = true;
            this.table3.Add(this.terraCachingCheck);
            Gtk.Table.TableChild w33 = ((Gtk.Table.TableChild)(this.table3[this.terraCachingCheck]));
            w33.TopAttach = ((uint)(1));
            w33.BottomAttach = ((uint)(2));
            w33.LeftAttach = ((uint)(1));
            w33.RightAttach = ((uint)(2));
            w33.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.wayMarkingCheck = new Gtk.CheckButton();
            this.wayMarkingCheck.CanFocus = true;
            this.wayMarkingCheck.Name = "wayMarkingCheck";
            this.wayMarkingCheck.Label = Mono.Unix.Catalog.GetString("Waymarking.com");
            this.wayMarkingCheck.DrawIndicator = true;
            this.wayMarkingCheck.UseUnderline = true;
            this.table3.Add(this.wayMarkingCheck);
            Gtk.Table.TableChild w34 = ((Gtk.Table.TableChild)(this.table3[this.wayMarkingCheck]));
            w34.TopAttach = ((uint)(1));
            w34.BottomAttach = ((uint)(2));
            w34.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment3.Add(this.table3);
            this.sourceFrame.Add(this.GtkAlignment3);
            this.vbox2.Add(this.sourceFrame);
            Gtk.Box.BoxChild w37 = ((Gtk.Box.BoxChild)(this.vbox2[this.sourceFrame]));
            w37.Position = 4;
            w37.Expand = false;
            this.GtkAlignment2.Add(this.vbox2);
            this.frame2.Add(this.GtkAlignment2);
            this.GtkLabel25 = new Gtk.Label();
            this.GtkLabel25.Name = "GtkLabel25";
            this.GtkLabel25.LabelProp = Mono.Unix.Catalog.GetString("<b>Cache Types</b>");
            this.GtkLabel25.UseMarkup = true;
            this.frame2.LabelWidget = this.GtkLabel25;
            this.vbox1.Add(this.frame2);
            Gtk.Box.BoxChild w40 = ((Gtk.Box.BoxChild)(this.vbox1[this.frame2]));
            w40.Position = 1;
            w40.Expand = false;
            w40.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
            this.terrainCheck.Toggled += new System.EventHandler(this.OnTerrToggle);
            this.diffCheck.Toggled += new System.EventHandler(this.OnDiffToggle);
            this.allCacheRadio.Toggled += new System.EventHandler(this.OnCacheToggle);
            this.providerCheck.Toggled += new System.EventHandler(this.OnSourceToggle);
        }
    }
}
