// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ocmgtk {
    
    
    public partial class OCMQueryPage3 {
        
        private Gtk.VBox vbox2;
        
        private Gtk.Frame frame6;
        
        private Gtk.Alignment GtkAlignment3;
        
        private Gtk.Table table3;
        
        private Gtk.CheckButton hiddenCheck;
        
        private Gtk.ComboBox hiddenCombo;
        
        private ocmgtk.DateWidget hiddenDateEntry;
        
        private Gtk.RadioButton placedAnyRadio;
        
        private Gtk.RadioButton placedByRadio;
        
        private Gtk.Entry placedEntry;
        
        private Gtk.Label GtkLabel14;
        
        private Gtk.Frame frame1;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.Table table1;
        
        private Gtk.CheckButton countryCheck;
        
        private Gtk.Entry countryEntry;
        
        private Gtk.CheckButton distCheck;
        
        private Gtk.Frame distFrame;
        
        private Gtk.Alignment GtkAlignment1;
        
        private Gtk.VBox vbox3;
        
        private Gtk.HBox hbox2;
        
        private Gtk.ComboBox distCombo;
        
        private Gtk.Entry distEntry;
        
        private Gtk.Label distMeasureLabel;
        
        private Gtk.RadioButton radiobutton1;
        
        private Gtk.HBox hbox3;
        
        private Gtk.RadioButton locRadio;
        
        private Gtk.ComboBox locationCombo;
        
        private Gtk.HBox hbox4;
        
        private Gtk.RadioButton posRadio;
        
        private ocmgtk.LocationWidget posLocation;
        
        private Gtk.CheckButton stateCheck;
        
        private Gtk.Entry stateEntry;
        
        private Gtk.Label GtkLabel8;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ocmgtk.OCMQueryPage3
            Stetic.BinContainer.Attach(this);
            this.Name = "ocmgtk.OCMQueryPage3";
            // Container child ocmgtk.OCMQueryPage3.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            this.vbox2.BorderWidth = ((uint)(6));
            // Container child vbox2.Gtk.Box+BoxChild
            this.frame6 = new Gtk.Frame();
            this.frame6.Name = "frame6";
            this.frame6.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame6.Gtk.Container+ContainerChild
            this.GtkAlignment3 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment3.Name = "GtkAlignment3";
            this.GtkAlignment3.LeftPadding = ((uint)(12));
            // Container child GtkAlignment3.Gtk.Container+ContainerChild
            this.table3 = new Gtk.Table(((uint)(3)), ((uint)(3)), false);
            this.table3.Name = "table3";
            this.table3.RowSpacing = ((uint)(6));
            this.table3.ColumnSpacing = ((uint)(6));
            // Container child table3.Gtk.Table+TableChild
            this.hiddenCheck = new Gtk.CheckButton();
            this.hiddenCheck.CanFocus = true;
            this.hiddenCheck.Name = "hiddenCheck";
            this.hiddenCheck.Label = Mono.Unix.Catalog.GetString("Hidden:");
            this.hiddenCheck.DrawIndicator = true;
            this.hiddenCheck.UseUnderline = true;
            this.table3.Add(this.hiddenCheck);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table3[this.hiddenCheck]));
            w1.TopAttach = ((uint)(2));
            w1.BottomAttach = ((uint)(3));
            w1.XOptions = ((Gtk.AttachOptions)(4));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.hiddenCombo = Gtk.ComboBox.NewText();
            this.hiddenCombo.AppendText(Mono.Unix.Catalog.GetString("On or before"));
            this.hiddenCombo.AppendText(Mono.Unix.Catalog.GetString("On or after"));
            this.hiddenCombo.Sensitive = false;
            this.hiddenCombo.Name = "hiddenCombo";
            this.hiddenCombo.Active = 0;
            this.table3.Add(this.hiddenCombo);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table3[this.hiddenCombo]));
            w2.TopAttach = ((uint)(2));
            w2.BottomAttach = ((uint)(3));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(2));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.hiddenDateEntry = new ocmgtk.DateWidget();
            this.hiddenDateEntry.Sensitive = false;
            this.hiddenDateEntry.Events = ((Gdk.EventMask)(256));
            this.hiddenDateEntry.Name = "hiddenDateEntry";
            this.hiddenDateEntry.IncludeTime = false;
            this.hiddenDateEntry.Date = new System.DateTime(0);
            this.table3.Add(this.hiddenDateEntry);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table3[this.hiddenDateEntry]));
            w3.TopAttach = ((uint)(2));
            w3.BottomAttach = ((uint)(3));
            w3.LeftAttach = ((uint)(2));
            w3.RightAttach = ((uint)(3));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.placedAnyRadio = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("Placed by anyone"));
            this.placedAnyRadio.CanFocus = true;
            this.placedAnyRadio.Name = "placedAnyRadio";
            this.placedAnyRadio.Active = true;
            this.placedAnyRadio.DrawIndicator = true;
            this.placedAnyRadio.UseUnderline = true;
            this.placedAnyRadio.Group = new GLib.SList(System.IntPtr.Zero);
            this.table3.Add(this.placedAnyRadio);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table3[this.placedAnyRadio]));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.placedByRadio = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("Placed by:"));
            this.placedByRadio.CanFocus = true;
            this.placedByRadio.Name = "placedByRadio";
            this.placedByRadio.DrawIndicator = true;
            this.placedByRadio.UseUnderline = true;
            this.placedByRadio.Group = this.placedAnyRadio.Group;
            this.table3.Add(this.placedByRadio);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table3[this.placedByRadio]));
            w5.TopAttach = ((uint)(1));
            w5.BottomAttach = ((uint)(2));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.placedEntry = new Gtk.Entry();
            this.placedEntry.Sensitive = false;
            this.placedEntry.CanFocus = true;
            this.placedEntry.Name = "placedEntry";
            this.placedEntry.IsEditable = true;
            this.placedEntry.InvisibleChar = '•';
            this.table3.Add(this.placedEntry);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table3[this.placedEntry]));
            w6.TopAttach = ((uint)(1));
            w6.BottomAttach = ((uint)(2));
            w6.LeftAttach = ((uint)(1));
            w6.RightAttach = ((uint)(3));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment3.Add(this.table3);
            this.frame6.Add(this.GtkAlignment3);
            this.GtkLabel14 = new Gtk.Label();
            this.GtkLabel14.Name = "GtkLabel14";
            this.GtkLabel14.LabelProp = Mono.Unix.Catalog.GetString("<b>Cache Placement</b>");
            this.GtkLabel14.UseMarkup = true;
            this.frame6.LabelWidget = this.GtkLabel14;
            this.vbox2.Add(this.frame6);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox2[this.frame6]));
            w9.Position = 0;
            w9.Expand = false;
            w9.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.frame1 = new Gtk.Frame();
            this.frame1.Name = "frame1";
            this.frame1.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame1.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.table1 = new Gtk.Table(((uint)(4)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.countryCheck = new Gtk.CheckButton();
            this.countryCheck.CanFocus = true;
            this.countryCheck.Name = "countryCheck";
            this.countryCheck.Label = Mono.Unix.Catalog.GetString("Country:");
            this.countryCheck.DrawIndicator = true;
            this.countryCheck.UseUnderline = true;
            this.table1.Add(this.countryCheck);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table1[this.countryCheck]));
            w10.XOptions = ((Gtk.AttachOptions)(4));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.countryEntry = new Gtk.Entry();
            this.countryEntry.Sensitive = false;
            this.countryEntry.CanFocus = true;
            this.countryEntry.Name = "countryEntry";
            this.countryEntry.IsEditable = true;
            this.countryEntry.InvisibleChar = '•';
            this.table1.Add(this.countryEntry);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table1[this.countryEntry]));
            w11.LeftAttach = ((uint)(1));
            w11.RightAttach = ((uint)(2));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.distCheck = new Gtk.CheckButton();
            this.distCheck.CanFocus = true;
            this.distCheck.Name = "distCheck";
            this.distCheck.Label = Mono.Unix.Catalog.GetString("Distance is:");
            this.distCheck.DrawIndicator = true;
            this.distCheck.UseUnderline = true;
            this.table1.Add(this.distCheck);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table1[this.distCheck]));
            w12.TopAttach = ((uint)(2));
            w12.BottomAttach = ((uint)(3));
            w12.XOptions = ((Gtk.AttachOptions)(4));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.distFrame = new Gtk.Frame();
            this.distFrame.Sensitive = false;
            this.distFrame.Name = "distFrame";
            this.distFrame.ShadowType = ((Gtk.ShadowType)(1));
            // Container child distFrame.Gtk.Container+ContainerChild
            this.GtkAlignment1 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment1.Name = "GtkAlignment1";
            this.GtkAlignment1.LeftPadding = ((uint)(12));
            // Container child GtkAlignment1.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            this.vbox3.BorderWidth = ((uint)(6));
            // Container child vbox3.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.distCombo = Gtk.ComboBox.NewText();
            this.distCombo.AppendText(Mono.Unix.Catalog.GetString("Less than"));
            this.distCombo.AppendText(Mono.Unix.Catalog.GetString("Greater than"));
            this.distCombo.AppendText(Mono.Unix.Catalog.GetString("Equal to"));
            this.distCombo.Name = "distCombo";
            this.distCombo.Active = 0;
            this.hbox2.Add(this.distCombo);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.hbox2[this.distCombo]));
            w13.Position = 0;
            w13.Expand = false;
            w13.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.distEntry = new Gtk.Entry();
            this.distEntry.CanFocus = true;
            this.distEntry.Name = "distEntry";
            this.distEntry.IsEditable = true;
            this.distEntry.InvisibleChar = '•';
            this.hbox2.Add(this.distEntry);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.hbox2[this.distEntry]));
            w14.Position = 1;
            // Container child hbox2.Gtk.Box+BoxChild
            this.distMeasureLabel = new Gtk.Label();
            this.distMeasureLabel.Name = "distMeasureLabel";
            this.distMeasureLabel.LabelProp = Mono.Unix.Catalog.GetString("km");
            this.hbox2.Add(this.distMeasureLabel);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbox2[this.distMeasureLabel]));
            w15.Position = 2;
            w15.Expand = false;
            this.vbox3.Add(this.hbox2);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
            w16.Position = 0;
            w16.Expand = false;
            w16.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.radiobutton1 = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("From current centre point"));
            this.radiobutton1.CanFocus = true;
            this.radiobutton1.Name = "radiobutton1";
            this.radiobutton1.Active = true;
            this.radiobutton1.DrawIndicator = true;
            this.radiobutton1.UseUnderline = true;
            this.radiobutton1.Group = new GLib.SList(System.IntPtr.Zero);
            this.vbox3.Add(this.radiobutton1);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.vbox3[this.radiobutton1]));
            w17.Position = 1;
            w17.Expand = false;
            w17.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.locRadio = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("From location:"));
            this.locRadio.CanFocus = true;
            this.locRadio.Name = "locRadio";
            this.locRadio.DrawIndicator = true;
            this.locRadio.UseUnderline = true;
            this.locRadio.Group = this.radiobutton1.Group;
            this.hbox3.Add(this.locRadio);
            Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.hbox3[this.locRadio]));
            w18.Position = 0;
            w18.Expand = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.locationCombo = Gtk.ComboBox.NewText();
            this.locationCombo.Sensitive = false;
            this.locationCombo.Name = "locationCombo";
            this.hbox3.Add(this.locationCombo);
            Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.hbox3[this.locationCombo]));
            w19.Position = 1;
            w19.Expand = false;
            w19.Fill = false;
            this.vbox3.Add(this.hbox3);
            Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
            w20.Position = 2;
            w20.Expand = false;
            w20.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hbox4 = new Gtk.HBox();
            this.hbox4.Name = "hbox4";
            this.hbox4.Spacing = 6;
            // Container child hbox4.Gtk.Box+BoxChild
            this.posRadio = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("From position:"));
            this.posRadio.CanFocus = true;
            this.posRadio.Name = "posRadio";
            this.posRadio.DrawIndicator = true;
            this.posRadio.UseUnderline = true;
            this.posRadio.Group = this.radiobutton1.Group;
            this.hbox4.Add(this.posRadio);
            Gtk.Box.BoxChild w21 = ((Gtk.Box.BoxChild)(this.hbox4[this.posRadio]));
            w21.Position = 0;
            // Container child hbox4.Gtk.Box+BoxChild
            this.posLocation = new ocmgtk.LocationWidget();
            this.posLocation.Sensitive = false;
            this.posLocation.Events = ((Gdk.EventMask)(256));
            this.posLocation.Name = "posLocation";
            this.posLocation.Latitude = 0;
            this.posLocation.Longitude = 0;
            this.hbox4.Add(this.posLocation);
            Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.hbox4[this.posLocation]));
            w22.Position = 1;
            w22.Expand = false;
            w22.Fill = false;
            this.vbox3.Add(this.hbox4);
            Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
            w23.Position = 3;
            w23.Expand = false;
            w23.Fill = false;
            this.GtkAlignment1.Add(this.vbox3);
            this.distFrame.Add(this.GtkAlignment1);
            this.table1.Add(this.distFrame);
            Gtk.Table.TableChild w26 = ((Gtk.Table.TableChild)(this.table1[this.distFrame]));
            w26.TopAttach = ((uint)(3));
            w26.BottomAttach = ((uint)(4));
            w26.RightAttach = ((uint)(2));
            w26.XOptions = ((Gtk.AttachOptions)(4));
            w26.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.stateCheck = new Gtk.CheckButton();
            this.stateCheck.CanFocus = true;
            this.stateCheck.Name = "stateCheck";
            this.stateCheck.Label = Mono.Unix.Catalog.GetString("State or province:");
            this.stateCheck.DrawIndicator = true;
            this.stateCheck.UseUnderline = true;
            this.table1.Add(this.stateCheck);
            Gtk.Table.TableChild w27 = ((Gtk.Table.TableChild)(this.table1[this.stateCheck]));
            w27.TopAttach = ((uint)(1));
            w27.BottomAttach = ((uint)(2));
            w27.XOptions = ((Gtk.AttachOptions)(4));
            w27.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.stateEntry = new Gtk.Entry();
            this.stateEntry.Sensitive = false;
            this.stateEntry.CanFocus = true;
            this.stateEntry.Name = "stateEntry";
            this.stateEntry.IsEditable = true;
            this.stateEntry.InvisibleChar = '•';
            this.table1.Add(this.stateEntry);
            Gtk.Table.TableChild w28 = ((Gtk.Table.TableChild)(this.table1[this.stateEntry]));
            w28.TopAttach = ((uint)(1));
            w28.BottomAttach = ((uint)(2));
            w28.LeftAttach = ((uint)(1));
            w28.RightAttach = ((uint)(2));
            w28.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment.Add(this.table1);
            this.frame1.Add(this.GtkAlignment);
            this.GtkLabel8 = new Gtk.Label();
            this.GtkLabel8.Name = "GtkLabel8";
            this.GtkLabel8.LabelProp = Mono.Unix.Catalog.GetString("<b>Cache Location</b>");
            this.GtkLabel8.UseMarkup = true;
            this.frame1.LabelWidget = this.GtkLabel8;
            this.vbox2.Add(this.frame1);
            Gtk.Box.BoxChild w31 = ((Gtk.Box.BoxChild)(this.vbox2[this.frame1]));
            w31.Position = 1;
            w31.Expand = false;
            w31.Fill = false;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
            this.placedByRadio.Toggled += new System.EventHandler(this.OnPlacedByToggle);
            this.hiddenCheck.Toggled += new System.EventHandler(this.OnHiddenToggle);
            this.stateCheck.Toggled += new System.EventHandler(this.OnStateCheckToggle);
            this.locRadio.Toggled += new System.EventHandler(this.OnLocationToggle);
            this.posRadio.Toggled += new System.EventHandler(this.OnPositionToggle);
            this.distCheck.Toggled += new System.EventHandler(this.OnDistanceToggle);
            this.countryCheck.Toggled += new System.EventHandler(this.OnCountryToggle);
        }
    }
}
