// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ocmgtk {
    
    
    public partial class ExportGPXDialog {
        
        private Gtk.Notebook notebook1;
        
        private Gtk.Alignment alignment1;
        
        private Gtk.FileChooserWidget fileChooser;
        
        private Gtk.Label label2;
        
        private Gtk.VBox vbox4;
        
        private Gtk.Frame frame4;
        
        private Gtk.Alignment GtkAlignment15;
        
        private Gtk.VBox vbox5;
        
        private Gtk.HBox hbox1;
        
        private Gtk.CheckButton limitCheck;
        
        private Gtk.Entry limitEntry;
        
        private Gtk.CheckButton includeChildrenCheck;
        
        private Gtk.CheckButton exportPaperlessDetails;
        
        private Gtk.CheckButton checkbutton1;
        
        private Gtk.CheckButton customSymbolsCheck;
        
        private Gtk.Label GtkLabel25;
        
        private Gtk.Frame paperlessFrame;
        
        private Gtk.Alignment GtkAlignment12;
        
        private Gtk.Table table5;
        
        private Gtk.CheckButton attrCheck;
        
        private Gtk.CheckButton logLimitCheck;
        
        private Gtk.Entry logLimitEntry;
        
        private Gtk.CheckButton usePlainTextCheck;
        
        private Gtk.Label GtkLabel20;
        
        private Gtk.Frame waypointFrame;
        
        private Gtk.Alignment GtkAlignment11;
        
        private Gtk.Table table3;
        
        private Gtk.ComboBox descMode;
        
        private Gtk.Label label1;
        
        private Gtk.Label label5;
        
        private Gtk.ComboBox nameMode;
        
        private Gtk.Label GtkLabel21;
        
        private Gtk.Label label4;
        
        private ocmgtk.WaypointOverrideWidget waypointSymbolWidget;
        
        private Gtk.Label symbolsPage;
        
        private Gtk.Button buttonCancel;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ocmgtk.ExportGPXDialog
            this.WidthRequest = 750;
            this.HeightRequest = 500;
            this.Name = "ocmgtk.ExportGPXDialog";
            this.Title = Mono.Unix.Catalog.GetString("Export GPX...");
            this.TypeHint = ((Gdk.WindowTypeHint)(1));
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.Modal = true;
            this.BorderWidth = ((uint)(6));
            this.Resizable = false;
            this.AllowGrow = false;
            this.SkipPagerHint = true;
            this.SkipTaskbarHint = true;
            // Internal child ocmgtk.ExportGPXDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.notebook1 = new Gtk.Notebook();
            this.notebook1.CanFocus = true;
            this.notebook1.Name = "notebook1";
            this.notebook1.CurrentPage = 1;
            this.notebook1.TabPos = ((Gtk.PositionType)(0));
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.alignment1 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment1.Name = "alignment1";
            this.alignment1.BorderWidth = ((uint)(6));
            // Container child alignment1.Gtk.Container+ContainerChild
            this.fileChooser = new Gtk.FileChooserWidget(((Gtk.FileChooserAction)(1)));
            this.fileChooser.Name = "fileChooser";
            this.fileChooser.DoOverwriteConfirmation = true;
            this.alignment1.Add(this.fileChooser);
            this.notebook1.Add(this.alignment1);
            // Notebook tab
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("File");
            this.notebook1.SetTabLabel(this.alignment1, this.label2);
            this.label2.ShowAll();
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.frame4 = new Gtk.Frame();
            this.frame4.Name = "frame4";
            this.frame4.ShadowType = ((Gtk.ShadowType)(0));
            this.frame4.BorderWidth = ((uint)(6));
            // Container child frame4.Gtk.Container+ContainerChild
            this.GtkAlignment15 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment15.Name = "GtkAlignment15";
            this.GtkAlignment15.LeftPadding = ((uint)(12));
            // Container child GtkAlignment15.Gtk.Container+ContainerChild
            this.vbox5 = new Gtk.VBox();
            this.vbox5.Name = "vbox5";
            this.vbox5.Spacing = 6;
            // Container child vbox5.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.limitCheck = new Gtk.CheckButton();
            this.limitCheck.CanFocus = true;
            this.limitCheck.Name = "limitCheck";
            this.limitCheck.Label = Mono.Unix.Catalog.GetString("Limit Number of Geocaches");
            this.limitCheck.DrawIndicator = true;
            this.limitCheck.UseUnderline = true;
            this.hbox1.Add(this.limitCheck);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox1[this.limitCheck]));
            w4.Position = 0;
            w4.Expand = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.limitEntry = new Gtk.Entry();
            this.limitEntry.CanFocus = true;
            this.limitEntry.Name = "limitEntry";
            this.limitEntry.Text = "1000";
            this.limitEntry.IsEditable = true;
            this.limitEntry.InvisibleChar = '•';
            this.hbox1.Add(this.limitEntry);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox1[this.limitEntry]));
            w5.Position = 1;
            this.vbox5.Add(this.hbox1);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox1]));
            w6.Position = 0;
            w6.Expand = false;
            w6.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.includeChildrenCheck = new Gtk.CheckButton();
            this.includeChildrenCheck.CanFocus = true;
            this.includeChildrenCheck.Name = "includeChildrenCheck";
            this.includeChildrenCheck.Label = Mono.Unix.Catalog.GetString("Include Child Waypoints");
            this.includeChildrenCheck.Active = true;
            this.includeChildrenCheck.DrawIndicator = true;
            this.includeChildrenCheck.UseUnderline = true;
            this.vbox5.Add(this.includeChildrenCheck);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox5[this.includeChildrenCheck]));
            w7.Position = 1;
            w7.Expand = false;
            w7.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.exportPaperlessDetails = new Gtk.CheckButton();
            this.exportPaperlessDetails.CanFocus = true;
            this.exportPaperlessDetails.Name = "exportPaperlessDetails";
            this.exportPaperlessDetails.Label = Mono.Unix.Catalog.GetString("Export Paperless Caching Details");
            this.exportPaperlessDetails.Active = true;
            this.exportPaperlessDetails.DrawIndicator = true;
            this.exportPaperlessDetails.UseUnderline = true;
            this.vbox5.Add(this.exportPaperlessDetails);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox5[this.exportPaperlessDetails]));
            w8.Position = 2;
            w8.Expand = false;
            w8.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.checkbutton1 = new Gtk.CheckButton();
            this.checkbutton1.Sensitive = false;
            this.checkbutton1.CanFocus = true;
            this.checkbutton1.Name = "checkbutton1";
            this.checkbutton1.Label = Mono.Unix.Catalog.GetString("Export Extra Fields in GPX");
            this.checkbutton1.DrawIndicator = true;
            this.checkbutton1.UseUnderline = true;
            this.vbox5.Add(this.checkbutton1);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox5[this.checkbutton1]));
            w9.Position = 3;
            w9.Expand = false;
            w9.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.customSymbolsCheck = new Gtk.CheckButton();
            this.customSymbolsCheck.CanFocus = true;
            this.customSymbolsCheck.Name = "customSymbolsCheck";
            this.customSymbolsCheck.Label = Mono.Unix.Catalog.GetString("Use Custom Waypoint Symbols");
            this.customSymbolsCheck.DrawIndicator = true;
            this.customSymbolsCheck.UseUnderline = true;
            this.vbox5.Add(this.customSymbolsCheck);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox5[this.customSymbolsCheck]));
            w10.Position = 4;
            w10.Expand = false;
            w10.Fill = false;
            this.GtkAlignment15.Add(this.vbox5);
            this.frame4.Add(this.GtkAlignment15);
            this.GtkLabel25 = new Gtk.Label();
            this.GtkLabel25.Name = "GtkLabel25";
            this.GtkLabel25.LabelProp = Mono.Unix.Catalog.GetString("<b>General</b>");
            this.GtkLabel25.UseMarkup = true;
            this.frame4.LabelWidget = this.GtkLabel25;
            this.vbox4.Add(this.frame4);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.vbox4[this.frame4]));
            w13.Position = 0;
            w13.Expand = false;
            w13.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.paperlessFrame = new Gtk.Frame();
            this.paperlessFrame.Name = "paperlessFrame";
            this.paperlessFrame.ShadowType = ((Gtk.ShadowType)(0));
            // Container child paperlessFrame.Gtk.Container+ContainerChild
            this.GtkAlignment12 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment12.Name = "GtkAlignment12";
            this.GtkAlignment12.LeftPadding = ((uint)(12));
            // Container child GtkAlignment12.Gtk.Container+ContainerChild
            this.table5 = new Gtk.Table(((uint)(3)), ((uint)(2)), false);
            this.table5.Name = "table5";
            this.table5.RowSpacing = ((uint)(6));
            this.table5.ColumnSpacing = ((uint)(6));
            this.table5.BorderWidth = ((uint)(6));
            // Container child table5.Gtk.Table+TableChild
            this.attrCheck = new Gtk.CheckButton();
            this.attrCheck.CanFocus = true;
            this.attrCheck.Name = "attrCheck";
            this.attrCheck.Label = Mono.Unix.Catalog.GetString("Include Attributes in Description");
            this.attrCheck.DrawIndicator = true;
            this.attrCheck.UseUnderline = true;
            this.table5.Add(this.attrCheck);
            Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table5[this.attrCheck]));
            w14.TopAttach = ((uint)(1));
            w14.BottomAttach = ((uint)(2));
            w14.RightAttach = ((uint)(2));
            w14.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.logLimitCheck = new Gtk.CheckButton();
            this.logLimitCheck.CanFocus = true;
            this.logLimitCheck.Name = "logLimitCheck";
            this.logLimitCheck.Label = Mono.Unix.Catalog.GetString("Limit Number of Logs");
            this.logLimitCheck.DrawIndicator = true;
            this.logLimitCheck.UseUnderline = true;
            this.table5.Add(this.logLimitCheck);
            Gtk.Table.TableChild w15 = ((Gtk.Table.TableChild)(this.table5[this.logLimitCheck]));
            w15.XOptions = ((Gtk.AttachOptions)(4));
            w15.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.logLimitEntry = new Gtk.Entry();
            this.logLimitEntry.Sensitive = false;
            this.logLimitEntry.CanFocus = true;
            this.logLimitEntry.Name = "logLimitEntry";
            this.logLimitEntry.Text = Mono.Unix.Catalog.GetString("5");
            this.logLimitEntry.IsEditable = true;
            this.logLimitEntry.InvisibleChar = '•';
            this.table5.Add(this.logLimitEntry);
            Gtk.Table.TableChild w16 = ((Gtk.Table.TableChild)(this.table5[this.logLimitEntry]));
            w16.LeftAttach = ((uint)(1));
            w16.RightAttach = ((uint)(2));
            w16.XOptions = ((Gtk.AttachOptions)(4));
            w16.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.usePlainTextCheck = new Gtk.CheckButton();
            this.usePlainTextCheck.CanFocus = true;
            this.usePlainTextCheck.Name = "usePlainTextCheck";
            this.usePlainTextCheck.Label = Mono.Unix.Catalog.GetString("Convert HTML to Plain Text");
            this.usePlainTextCheck.DrawIndicator = true;
            this.usePlainTextCheck.UseUnderline = true;
            this.table5.Add(this.usePlainTextCheck);
            Gtk.Table.TableChild w17 = ((Gtk.Table.TableChild)(this.table5[this.usePlainTextCheck]));
            w17.TopAttach = ((uint)(2));
            w17.BottomAttach = ((uint)(3));
            w17.RightAttach = ((uint)(2));
            w17.XOptions = ((Gtk.AttachOptions)(4));
            w17.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment12.Add(this.table5);
            this.paperlessFrame.Add(this.GtkAlignment12);
            this.GtkLabel20 = new Gtk.Label();
            this.GtkLabel20.Name = "GtkLabel20";
            this.GtkLabel20.LabelProp = Mono.Unix.Catalog.GetString("<b>Paperless Options</b>");
            this.GtkLabel20.UseMarkup = true;
            this.paperlessFrame.LabelWidget = this.GtkLabel20;
            this.vbox4.Add(this.paperlessFrame);
            Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.vbox4[this.paperlessFrame]));
            w20.Position = 1;
            w20.Expand = false;
            w20.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.waypointFrame = new Gtk.Frame();
            this.waypointFrame.Name = "waypointFrame";
            this.waypointFrame.ShadowType = ((Gtk.ShadowType)(0));
            // Container child waypointFrame.Gtk.Container+ContainerChild
            this.GtkAlignment11 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment11.Name = "GtkAlignment11";
            this.GtkAlignment11.LeftPadding = ((uint)(12));
            // Container child GtkAlignment11.Gtk.Container+ContainerChild
            this.table3 = new Gtk.Table(((uint)(2)), ((uint)(2)), false);
            this.table3.Name = "table3";
            this.table3.RowSpacing = ((uint)(6));
            this.table3.ColumnSpacing = ((uint)(6));
            this.table3.BorderWidth = ((uint)(6));
            // Container child table3.Gtk.Table+TableChild
            this.descMode = Gtk.ComboBox.NewText();
            this.descMode.AppendText(Mono.Unix.Catalog.GetString("Cache Name"));
            this.descMode.AppendText(Mono.Unix.Catalog.GetString("Cache Code/Size/Hint"));
            this.descMode.AppendText(Mono.Unix.Catalog.GetString("Cache Code/Size/Type"));
            this.descMode.Name = "descMode";
            this.descMode.Active = 0;
            this.table3.Add(this.descMode);
            Gtk.Table.TableChild w21 = ((Gtk.Table.TableChild)(this.table3[this.descMode]));
            w21.TopAttach = ((uint)(1));
            w21.BottomAttach = ((uint)(2));
            w21.LeftAttach = ((uint)(1));
            w21.RightAttach = ((uint)(2));
            w21.XOptions = ((Gtk.AttachOptions)(4));
            w21.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.Xalign = 0F;
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Waypoint Name Format:");
            this.table3.Add(this.label1);
            Gtk.Table.TableChild w22 = ((Gtk.Table.TableChild)(this.table3[this.label1]));
            w22.XOptions = ((Gtk.AttachOptions)(4));
            w22.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.Xalign = 0F;
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Waypoint Description Format:");
            this.table3.Add(this.label5);
            Gtk.Table.TableChild w23 = ((Gtk.Table.TableChild)(this.table3[this.label5]));
            w23.TopAttach = ((uint)(1));
            w23.BottomAttach = ((uint)(2));
            w23.XOptions = ((Gtk.AttachOptions)(4));
            w23.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.nameMode = Gtk.ComboBox.NewText();
            this.nameMode.AppendText(Mono.Unix.Catalog.GetString("Cache Code"));
            this.nameMode.AppendText(Mono.Unix.Catalog.GetString("Cache Name"));
            this.nameMode.Name = "nameMode";
            this.nameMode.Active = 0;
            this.table3.Add(this.nameMode);
            Gtk.Table.TableChild w24 = ((Gtk.Table.TableChild)(this.table3[this.nameMode]));
            w24.LeftAttach = ((uint)(1));
            w24.RightAttach = ((uint)(2));
            w24.XOptions = ((Gtk.AttachOptions)(4));
            w24.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment11.Add(this.table3);
            this.waypointFrame.Add(this.GtkAlignment11);
            this.GtkLabel21 = new Gtk.Label();
            this.GtkLabel21.Name = "GtkLabel21";
            this.GtkLabel21.LabelProp = Mono.Unix.Catalog.GetString("<b>Waypoint Options</b>");
            this.GtkLabel21.UseMarkup = true;
            this.waypointFrame.LabelWidget = this.GtkLabel21;
            this.vbox4.Add(this.waypointFrame);
            Gtk.Box.BoxChild w27 = ((Gtk.Box.BoxChild)(this.vbox4[this.waypointFrame]));
            w27.Position = 2;
            w27.Expand = false;
            w27.Fill = false;
            this.notebook1.Add(this.vbox4);
            Gtk.Notebook.NotebookChild w28 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox4]));
            w28.Position = 1;
            // Notebook tab
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("Options");
            this.notebook1.SetTabLabel(this.vbox4, this.label4);
            this.label4.ShowAll();
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.waypointSymbolWidget = new ocmgtk.WaypointOverrideWidget();
            this.waypointSymbolWidget.Events = ((Gdk.EventMask)(256));
            this.waypointSymbolWidget.Name = "waypointSymbolWidget";
            this.notebook1.Add(this.waypointSymbolWidget);
            Gtk.Notebook.NotebookChild w29 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.waypointSymbolWidget]));
            w29.Position = 2;
            // Notebook tab
            this.symbolsPage = new Gtk.Label();
            this.symbolsPage.Name = "symbolsPage";
            this.symbolsPage.LabelProp = Mono.Unix.Catalog.GetString("Waypoint Symbols");
            this.notebook1.SetTabLabel(this.waypointSymbolWidget, this.symbolsPage);
            this.symbolsPage.ShowAll();
            w1.Add(this.notebook1);
            Gtk.Box.BoxChild w30 = ((Gtk.Box.BoxChild)(w1[this.notebook1]));
            w30.Position = 0;
            // Internal child ocmgtk.ExportGPXDialog.ActionArea
            Gtk.HButtonBox w31 = this.ActionArea;
            w31.Name = "dialog1_ActionArea";
            w31.Spacing = 10;
            w31.BorderWidth = ((uint)(5));
            w31.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonCancel = new Gtk.Button();
            this.buttonCancel.CanDefault = true;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseStock = true;
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = "gtk-cancel";
            this.AddActionWidget(this.buttonCancel, -6);
            Gtk.ButtonBox.ButtonBoxChild w32 = ((Gtk.ButtonBox.ButtonBoxChild)(w31[this.buttonCancel]));
            w32.Expand = false;
            w32.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-ok";
            this.AddActionWidget(this.buttonOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w33 = ((Gtk.ButtonBox.ButtonBoxChild)(w31[this.buttonOk]));
            w33.Position = 1;
            w33.Expand = false;
            w33.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 762;
            this.DefaultHeight = 527;
            this.Show();
            this.limitCheck.Toggled += new System.EventHandler(this.OnLimitToggle);
            this.exportPaperlessDetails.Toggled += new System.EventHandler(this.OnPaperlessToggle);
            this.logLimitCheck.Toggled += new System.EventHandler(this.OnLogLimitToggle);
        }
    }
}
