
// This file has been generated by the GUI designer. Do not modify.
namespace ocmgtk
{
	public partial class LocationWidget
	{
		private global::Gtk.Table widgetTable;
		
		private global::Gtk.Button button9;
		
		private global::Gtk.Image editIcon;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label latLabel;
		
		private global::ocmgtk.CoordinateWidget latWidget;
		
		private global::Gtk.Label lonLabel;
		
		private global::ocmgtk.CoordinateWidget lonWidget;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ocmgtk.LocationWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "ocmgtk.LocationWidget";
			// Container child ocmgtk.LocationWidget.Gtk.Container+ContainerChild
			this.widgetTable = new global::Gtk.Table (((uint)(2)), ((uint)(4)), false);
			this.widgetTable.Name = "widgetTable";
			this.widgetTable.RowSpacing = ((uint)(6));
			this.widgetTable.ColumnSpacing = ((uint)(6));
			// Container child widgetTable.Gtk.Table+TableChild
			this.button9 = new global::Gtk.Button ();
			this.button9.CanFocus = true;
			this.button9.Name = "button9";
			// Container child button9.Gtk.Container+ContainerChild
			this.editIcon = new global::Gtk.Image ();
			this.editIcon.Name = "editIcon";
			this.editIcon.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Button);
			this.button9.Add (this.editIcon);
			this.widgetTable.Add (this.button9);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.widgetTable [this.button9]));
			w2.LeftAttach = ((uint)(2));
			w2.RightAttach = ((uint)(3));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child widgetTable.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.widgetTable.Add (this.label1);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.widgetTable [this.label1]));
			w3.LeftAttach = ((uint)(3));
			w3.RightAttach = ((uint)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child widgetTable.Gtk.Table+TableChild
			this.latLabel = new global::Gtk.Label ();
			this.latLabel.Name = "latLabel";
			this.latLabel.Xalign = 0F;
			this.latLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Latitude:");
			this.widgetTable.Add (this.latLabel);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.widgetTable [this.latLabel]));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child widgetTable.Gtk.Table+TableChild
			this.latWidget = new global::ocmgtk.CoordinateWidget ();
			this.latWidget.Events = ((global::Gdk.EventMask)(256));
			this.latWidget.Name = "latWidget";
			this.widgetTable.Add (this.latWidget);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.widgetTable [this.latWidget]));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child widgetTable.Gtk.Table+TableChild
			this.lonLabel = new global::Gtk.Label ();
			this.lonLabel.Name = "lonLabel";
			this.lonLabel.Xalign = 0F;
			this.lonLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Longitude:");
			this.widgetTable.Add (this.lonLabel);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.widgetTable [this.lonLabel]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child widgetTable.Gtk.Table+TableChild
			this.lonWidget = new global::ocmgtk.CoordinateWidget ();
			this.lonWidget.Events = ((global::Gdk.EventMask)(256));
			this.lonWidget.Name = "lonWidget";
			this.widgetTable.Add (this.lonWidget);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.widgetTable [this.lonWidget]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.widgetTable);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.button9.Clicked += new global::System.EventHandler (this.OnEditClicked);
		}
	}
}
