// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ocmgtk {
    
    
    public partial class DateWidget {
        
        private Gtk.HBox hbox1;
        
        private Gtk.Entry dateField;
        
        private Gtk.Button calButton;
        
        private Gtk.Image image2;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ocmgtk.DateWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "ocmgtk.DateWidget";
            // Container child ocmgtk.DateWidget.Gtk.Container+ContainerChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.dateField = new Gtk.Entry();
            this.dateField.CanFocus = true;
            this.dateField.Name = "dateField";
            this.dateField.IsEditable = true;
            this.dateField.InvisibleChar = '•';
            this.hbox1.Add(this.dateField);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox1[this.dateField]));
            w1.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.calButton = new Gtk.Button();
            this.calButton.CanFocus = true;
            this.calButton.Name = "calButton";
            // Container child calButton.Gtk.Container+ContainerChild
            this.image2 = new Gtk.Image();
            this.image2.Name = "image2";
            this.image2.Pixbuf = Stetic.IconLoader.LoadIcon(this, "stock_calendar", Gtk.IconSize.Menu, 16);
            this.calButton.Add(this.image2);
            this.calButton.Label = null;
            this.hbox1.Add(this.calButton);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.calButton]));
            w3.Position = 1;
            w3.Expand = false;
            w3.Fill = false;
            this.Add(this.hbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
            this.calButton.Clicked += new System.EventHandler(this.OnCallClicked);
        }
    }
}
