// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ocmgtk {
    
    
    public partial class ImagesWidget {
        
        private Gtk.VBox vbox2;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Image image33;
        
        private Gtk.Label fileLabel;
        
        private Gtk.HBox hbox1;
        
        private Gtk.ScrolledWindow scrolledwindow1;
        
        private Gtk.IconView imagesView;
        
        private Gtk.VButtonBox vbuttonbox1;
        
        private Gtk.Button viewButton;
        
        private Gtk.Button GrabImagesButton;
        
        private Gtk.Button openFolderButton;
        
        private Gtk.Button buttonRefresh;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ocmgtk.ImagesWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "ocmgtk.ImagesWidget";
            // Container child ocmgtk.ImagesWidget.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            this.vbox2.BorderWidth = ((uint)(6));
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.image33 = new Gtk.Image();
            this.image33.Name = "image33";
            this.image33.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-dialog-info", Gtk.IconSize.LargeToolbar, 24);
            this.hbox2.Add(this.image33);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox2[this.image33]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.fileLabel = new Gtk.Label();
            this.fileLabel.Name = "fileLabel";
            this.fileLabel.LabelProp = "<file location>";
            this.hbox2.Add(this.fileLabel);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox2[this.fileLabel]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            this.vbox2.Add(this.hbox2);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            this.hbox1.BorderWidth = ((uint)(6));
            // Container child hbox1.Gtk.Box+BoxChild
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow1.Gtk.Container+ContainerChild
            this.imagesView = new Gtk.IconView();
            this.imagesView.CanFocus = true;
            this.imagesView.Name = "imagesView";
            this.scrolledwindow1.Add(this.imagesView);
            this.hbox1.Add(this.scrolledwindow1);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox1[this.scrolledwindow1]));
            w5.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.vbuttonbox1 = new Gtk.VButtonBox();
            this.vbuttonbox1.Name = "vbuttonbox1";
            this.vbuttonbox1.Spacing = 6;
            this.vbuttonbox1.LayoutStyle = ((Gtk.ButtonBoxStyle)(3));
            // Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
            this.viewButton = new Gtk.Button();
            this.viewButton.Sensitive = false;
            this.viewButton.CanFocus = true;
            this.viewButton.Name = "viewButton";
            this.viewButton.UseUnderline = true;
            this.viewButton.Label = Mono.Unix.Catalog.GetString("View");
            this.vbuttonbox1.Add(this.viewButton);
            Gtk.ButtonBox.ButtonBoxChild w6 = ((Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.viewButton]));
            w6.Expand = false;
            w6.Fill = false;
            // Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
            this.GrabImagesButton = new Gtk.Button();
            this.GrabImagesButton.CanFocus = true;
            this.GrabImagesButton.Name = "GrabImagesButton";
            this.GrabImagesButton.UseUnderline = true;
            this.GrabImagesButton.Label = Mono.Unix.Catalog.GetString("Grab Images...");
            this.vbuttonbox1.Add(this.GrabImagesButton);
            Gtk.ButtonBox.ButtonBoxChild w7 = ((Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.GrabImagesButton]));
            w7.Position = 1;
            w7.Expand = false;
            w7.Fill = false;
            // Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
            this.openFolderButton = new Gtk.Button();
            this.openFolderButton.CanFocus = true;
            this.openFolderButton.Name = "openFolderButton";
            this.openFolderButton.UseUnderline = true;
            this.openFolderButton.Label = Mono.Unix.Catalog.GetString("Open Folder");
            this.vbuttonbox1.Add(this.openFolderButton);
            Gtk.ButtonBox.ButtonBoxChild w8 = ((Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.openFolderButton]));
            w8.Position = 2;
            w8.Expand = false;
            w8.Fill = false;
            // Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
            this.buttonRefresh = new Gtk.Button();
            this.buttonRefresh.CanFocus = true;
            this.buttonRefresh.Name = "buttonRefresh";
            this.buttonRefresh.UseStock = true;
            this.buttonRefresh.UseUnderline = true;
            this.buttonRefresh.Label = "gtk-refresh";
            this.vbuttonbox1.Add(this.buttonRefresh);
            Gtk.ButtonBox.ButtonBoxChild w9 = ((Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.buttonRefresh]));
            w9.Position = 3;
            w9.Expand = false;
            w9.Fill = false;
            this.hbox1.Add(this.vbuttonbox1);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbuttonbox1]));
            w10.Position = 1;
            w10.Expand = false;
            w10.Fill = false;
            this.vbox2.Add(this.hbox1);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
            w11.Position = 1;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
            this.imagesView.ItemActivated += new Gtk.ItemActivatedHandler(this.OnDoubleClick);
            this.viewButton.Clicked += new System.EventHandler(this.OnViewClick);
            this.GrabImagesButton.Clicked += new System.EventHandler(this.OnGrabImagesClick);
            this.openFolderButton.Clicked += new System.EventHandler(this.OnOpenFolderClick);
            this.buttonRefresh.Clicked += new System.EventHandler(this.OnRefesh);
        }
    }
}
