
// This file has been generated by the GUI designer. Do not modify.
namespace ocmgtk
{
	public partial class WaypointOverrideWidget
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ocmgtk.WaypointOverrideWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "ocmgtk.WaypointOverrideWidget";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
