// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ocmgtk {
    
    
    public partial class CalendarWindow {
        
        private Gtk.Calendar cal;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ocmgtk.CalendarWindow
            this.Name = "ocmgtk.CalendarWindow";
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.Decorated = false;
            this.DestroyWithParent = true;
            // Internal child ocmgtk.CalendarWindow.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.cal = new Gtk.Calendar();
            this.cal.CanFocus = true;
            this.cal.Name = "cal";
            this.cal.DisplayOptions = ((Gtk.CalendarDisplayOptions)(35));
            w1.Add(this.cal);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(w1[this.cal]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Internal child ocmgtk.CalendarWindow.ActionArea
            Gtk.HButtonBox w3 = this.ActionArea;
            w3.Name = "dialog1_ActionArea";
            w3.Spacing = 10;
            w3.BorderWidth = ((uint)(5));
            w3.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-ok";
            this.AddActionWidget(this.buttonOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w4 = ((Gtk.ButtonBox.ButtonBoxChild)(w3[this.buttonOk]));
            w4.Expand = false;
            w4.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 228;
            this.DefaultHeight = 271;
            this.Show();
            this.cal.DaySelectedDoubleClick += new System.EventHandler(this.OnCalDClick);
            this.buttonOk.Clicked += new System.EventHandler(this.OnClicked);
        }
    }
}
