
// This file has been generated by the GUI designer. Do not modify.
namespace ocmgtk
{
	public partial class OCMQueryPage3
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Frame frame6;
		
		private global::Gtk.Alignment GtkAlignment3;
		
		private global::Gtk.Table table3;
		
		private global::Gtk.CheckButton hiddenCheck;
		
		private global::Gtk.ComboBox hiddenCombo;
		
		private global::ocmgtk.DateWidget hiddenDateEntry;
		
		private global::Gtk.RadioButton placedAnyRadio;
		
		private global::Gtk.RadioButton placedByRadio;
		
		private global::Gtk.Entry placedEntry;
		
		private global::Gtk.Label GtkLabel14;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.CheckButton countryCheck;
		
		private global::Gtk.Entry countryEntry;
		
		private global::Gtk.CheckButton distCheck;
		
		private global::Gtk.Frame distFrame;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.ComboBox distCombo;
		
		private global::Gtk.Entry distEntry;
		
		private global::Gtk.Label distMeasureLabel;
		
		private global::Gtk.RadioButton radiobutton1;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.RadioButton locRadio;
		
		private global::Gtk.ComboBox locationCombo;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.RadioButton posRadio;
		
		private global::ocmgtk.LocationWidget posLocation;
		
		private global::Gtk.CheckButton stateCheck;
		
		private global::Gtk.Entry stateEntry;
		
		private global::Gtk.Label GtkLabel8;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ocmgtk.OCMQueryPage3
			global::Stetic.BinContainer.Attach (this);
			this.Name = "ocmgtk.OCMQueryPage3";
			// Container child ocmgtk.OCMQueryPage3.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(6));
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame6 = new global::Gtk.Frame ();
			this.frame6.Name = "frame6";
			this.frame6.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame6.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.table3 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.hiddenCheck = new global::Gtk.CheckButton ();
			this.hiddenCheck.CanFocus = true;
			this.hiddenCheck.Name = "hiddenCheck";
			this.hiddenCheck.Label = global::Mono.Unix.Catalog.GetString ("Hidden:");
			this.hiddenCheck.DrawIndicator = true;
			this.hiddenCheck.UseUnderline = true;
			this.table3.Add (this.hiddenCheck);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table3 [this.hiddenCheck]));
			w1.TopAttach = ((uint)(2));
			w1.BottomAttach = ((uint)(3));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.hiddenCombo = global::Gtk.ComboBox.NewText ();
			this.hiddenCombo.AppendText (global::Mono.Unix.Catalog.GetString ("On or before"));
			this.hiddenCombo.AppendText (global::Mono.Unix.Catalog.GetString ("On or after"));
			this.hiddenCombo.Sensitive = false;
			this.hiddenCombo.Name = "hiddenCombo";
			this.hiddenCombo.Active = 0;
			this.table3.Add (this.hiddenCombo);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table3 [this.hiddenCombo]));
			w2.TopAttach = ((uint)(2));
			w2.BottomAttach = ((uint)(3));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.hiddenDateEntry = null;
			this.table3.Add (this.hiddenDateEntry);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3 [this.hiddenDateEntry]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(2));
			w3.RightAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.placedAnyRadio = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Placed by anyone"));
			this.placedAnyRadio.CanFocus = true;
			this.placedAnyRadio.Name = "placedAnyRadio";
			this.placedAnyRadio.Active = true;
			this.placedAnyRadio.DrawIndicator = true;
			this.placedAnyRadio.UseUnderline = true;
			this.placedAnyRadio.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.table3.Add (this.placedAnyRadio);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3 [this.placedAnyRadio]));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.placedByRadio = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Placed by:"));
			this.placedByRadio.CanFocus = true;
			this.placedByRadio.Name = "placedByRadio";
			this.placedByRadio.DrawIndicator = true;
			this.placedByRadio.UseUnderline = true;
			this.placedByRadio.Group = this.placedAnyRadio.Group;
			this.table3.Add (this.placedByRadio);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table3 [this.placedByRadio]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.placedEntry = new global::Gtk.Entry ();
			this.placedEntry.Sensitive = false;
			this.placedEntry.CanFocus = true;
			this.placedEntry.Name = "placedEntry";
			this.placedEntry.IsEditable = true;
			this.placedEntry.InvisibleChar = '•';
			this.table3.Add (this.placedEntry);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table3 [this.placedEntry]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(3));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment3.Add (this.table3);
			this.frame6.Add (this.GtkAlignment3);
			this.GtkLabel14 = new global::Gtk.Label ();
			this.GtkLabel14.Name = "GtkLabel14";
			this.GtkLabel14.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Cache Placement</b>");
			this.GtkLabel14.UseMarkup = true;
			this.frame6.LabelWidget = this.GtkLabel14;
			this.vbox2.Add (this.frame6);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame6]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(4)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.countryCheck = new global::Gtk.CheckButton ();
			this.countryCheck.CanFocus = true;
			this.countryCheck.Name = "countryCheck";
			this.countryCheck.Label = global::Mono.Unix.Catalog.GetString ("Country:");
			this.countryCheck.DrawIndicator = true;
			this.countryCheck.UseUnderline = true;
			this.table1.Add (this.countryCheck);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.countryCheck]));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.countryEntry = new global::Gtk.Entry ();
			this.countryEntry.Sensitive = false;
			this.countryEntry.CanFocus = true;
			this.countryEntry.Name = "countryEntry";
			this.countryEntry.IsEditable = true;
			this.countryEntry.InvisibleChar = '•';
			this.table1.Add (this.countryEntry);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.countryEntry]));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.distCheck = new global::Gtk.CheckButton ();
			this.distCheck.CanFocus = true;
			this.distCheck.Name = "distCheck";
			this.distCheck.Label = global::Mono.Unix.Catalog.GetString ("Distance is:");
			this.distCheck.DrawIndicator = true;
			this.distCheck.UseUnderline = true;
			this.table1.Add (this.distCheck);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.distCheck]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.distFrame = new global::Gtk.Frame ();
			this.distFrame.Sensitive = false;
			this.distFrame.Name = "distFrame";
			this.distFrame.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child distFrame.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			this.vbox3.BorderWidth = ((uint)(6));
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.distCombo = global::Gtk.ComboBox.NewText ();
			this.distCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Less than"));
			this.distCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Greater than"));
			this.distCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Equal to"));
			this.distCombo.Name = "distCombo";
			this.distCombo.Active = 0;
			this.hbox2.Add (this.distCombo);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.distCombo]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.distEntry = new global::Gtk.Entry ();
			this.distEntry.CanFocus = true;
			this.distEntry.Name = "distEntry";
			this.distEntry.IsEditable = true;
			this.distEntry.InvisibleChar = '•';
			this.hbox2.Add (this.distEntry);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.distEntry]));
			w14.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.distMeasureLabel = new global::Gtk.Label ();
			this.distMeasureLabel.Name = "distMeasureLabel";
			this.distMeasureLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("km");
			this.hbox2.Add (this.distMeasureLabel);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.distMeasureLabel]));
			w15.Position = 2;
			w15.Expand = false;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.radiobutton1 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("From current centre point"));
			this.radiobutton1.CanFocus = true;
			this.radiobutton1.Name = "radiobutton1";
			this.radiobutton1.Active = true;
			this.radiobutton1.DrawIndicator = true;
			this.radiobutton1.UseUnderline = true;
			this.radiobutton1.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.vbox3.Add (this.radiobutton1);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.radiobutton1]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.locRadio = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("From location:"));
			this.locRadio.CanFocus = true;
			this.locRadio.Name = "locRadio";
			this.locRadio.DrawIndicator = true;
			this.locRadio.UseUnderline = true;
			this.locRadio.Group = this.radiobutton1.Group;
			this.hbox3.Add (this.locRadio);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.locRadio]));
			w18.Position = 0;
			w18.Expand = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.locationCombo = global::Gtk.ComboBox.NewText ();
			this.locationCombo.Sensitive = false;
			this.locationCombo.Name = "locationCombo";
			this.hbox3.Add (this.locationCombo);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.locationCombo]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
			w20.Position = 2;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.posRadio = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("From position:"));
			this.posRadio.CanFocus = true;
			this.posRadio.Name = "posRadio";
			this.posRadio.DrawIndicator = true;
			this.posRadio.UseUnderline = true;
			this.posRadio.Group = this.radiobutton1.Group;
			this.hbox4.Add (this.posRadio);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.posRadio]));
			w21.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.posLocation = null;
			this.hbox4.Add (this.posLocation);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.posLocation]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.vbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
			w23.Position = 3;
			w23.Expand = false;
			w23.Fill = false;
			this.GtkAlignment1.Add (this.vbox3);
			this.distFrame.Add (this.GtkAlignment1);
			this.table1.Add (this.distFrame);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table1 [this.distFrame]));
			w26.TopAttach = ((uint)(3));
			w26.BottomAttach = ((uint)(4));
			w26.RightAttach = ((uint)(2));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.stateCheck = new global::Gtk.CheckButton ();
			this.stateCheck.CanFocus = true;
			this.stateCheck.Name = "stateCheck";
			this.stateCheck.Label = global::Mono.Unix.Catalog.GetString ("State or province:");
			this.stateCheck.DrawIndicator = true;
			this.stateCheck.UseUnderline = true;
			this.table1.Add (this.stateCheck);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1 [this.stateCheck]));
			w27.TopAttach = ((uint)(1));
			w27.BottomAttach = ((uint)(2));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.stateEntry = new global::Gtk.Entry ();
			this.stateEntry.Sensitive = false;
			this.stateEntry.CanFocus = true;
			this.stateEntry.Name = "stateEntry";
			this.stateEntry.IsEditable = true;
			this.stateEntry.InvisibleChar = '•';
			this.table1.Add (this.stateEntry);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table1 [this.stateEntry]));
			w28.TopAttach = ((uint)(1));
			w28.BottomAttach = ((uint)(2));
			w28.LeftAttach = ((uint)(1));
			w28.RightAttach = ((uint)(2));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment.Add (this.table1);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel8 = new global::Gtk.Label ();
			this.GtkLabel8.Name = "GtkLabel8";
			this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Cache Location</b>");
			this.GtkLabel8.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel8;
			this.vbox2.Add (this.frame1);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame1]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.placedByRadio.Toggled += new global::System.EventHandler (this.OnPlacedByToggle);
			this.hiddenCheck.Toggled += new global::System.EventHandler (this.OnHiddenToggle);
			this.stateCheck.Toggled += new global::System.EventHandler (this.OnStateCheckToggle);
			this.locRadio.Toggled += new global::System.EventHandler (this.OnLocationToggle);
			this.posRadio.Toggled += new global::System.EventHandler (this.OnPositionToggle);
			this.distCheck.Toggled += new global::System.EventHandler (this.OnDistanceToggle);
			this.countryCheck.Toggled += new global::System.EventHandler (this.OnCountryToggle);
		}
	}
}
