
// This file has been generated by the GUI designer. Do not modify.
namespace ocmgtk
{
	public partial class OCMQueryPage6
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.CheckButton lastUpdateCheck;
		
		private global::Gtk.Frame updateFrame;
		
		private global::Gtk.Alignment GtkAlignment2;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.ComboBox lastUpdateCombo;
		
		private global::ocmgtk.DateWidget lastUpdateDate;
		
		private global::Gtk.RadioButton lUpdateDate;
		
		private global::Gtk.RadioButton lUpdateWithin;
		
		private global::Gtk.Entry lupdatewithinEntry;
		
		private global::Gtk.Entry nupdatedWithinEntry;
		
		private global::Gtk.RadioButton nUpdateWithin;
		
		private global::Gtk.Label GtkLabel4;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::Gtk.Table table2;
		
		private global::Gtk.CheckButton foundCheck;
		
		private global::Gtk.ComboBox foundCombo;
		
		private global::ocmgtk.DateWidget foundDateEntry;
		
		private global::Gtk.CheckButton lFoundAnyOneCheck;
		
		private global::Gtk.ComboBox lFoundAnyoneCombo;
		
		private global::ocmgtk.DateWidget lFoundAnyoneDate;
		
		private global::Gtk.Label GtkLabel7;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ocmgtk.OCMQueryPage6
			global::Stetic.BinContainer.Attach (this);
			this.Name = "ocmgtk.OCMQueryPage6";
			// Container child ocmgtk.OCMQueryPage6.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(6));
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.lastUpdateCheck = new global::Gtk.CheckButton ();
			this.lastUpdateCheck.CanFocus = true;
			this.lastUpdateCheck.Name = "lastUpdateCheck";
			this.lastUpdateCheck.Label = global::Mono.Unix.Catalog.GetString ("Condition matches:");
			this.lastUpdateCheck.DrawIndicator = true;
			this.lastUpdateCheck.UseUnderline = true;
			this.vbox3.Add (this.lastUpdateCheck);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lastUpdateCheck]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.updateFrame = new global::Gtk.Frame ();
			this.updateFrame.Sensitive = false;
			this.updateFrame.Name = "updateFrame";
			this.updateFrame.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child updateFrame.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table1.BorderWidth = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("days");
			this.table1.Add (this.label3);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.label3]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(2));
			w2.RightAttach = ((uint)(3));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("days");
			this.table1.Add (this.label4);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.label4]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(2));
			w3.RightAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lastUpdateCombo = global::Gtk.ComboBox.NewText ();
			this.lastUpdateCombo.AppendText (global::Mono.Unix.Catalog.GetString ("On or before"));
			this.lastUpdateCombo.AppendText (global::Mono.Unix.Catalog.GetString ("On or after"));
			this.lastUpdateCombo.Name = "lastUpdateCombo";
			this.lastUpdateCombo.Active = 0;
			this.table1.Add (this.lastUpdateCombo);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.lastUpdateCombo]));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lastUpdateDate = null;
			this.table1.Add (this.lastUpdateDate);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.lastUpdateDate]));
			w5.LeftAttach = ((uint)(2));
			w5.RightAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lUpdateDate = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Last update date:"));
			this.lUpdateDate.CanFocus = true;
			this.lUpdateDate.Name = "lUpdateDate";
			this.lUpdateDate.Active = true;
			this.lUpdateDate.DrawIndicator = true;
			this.lUpdateDate.UseUnderline = true;
			this.lUpdateDate.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.table1.Add (this.lUpdateDate);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.lUpdateDate]));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lUpdateWithin = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Last updated within:"));
			this.lUpdateWithin.CanFocus = true;
			this.lUpdateWithin.Name = "lUpdateWithin";
			this.lUpdateWithin.DrawIndicator = true;
			this.lUpdateWithin.UseUnderline = true;
			this.lUpdateWithin.Group = this.lUpdateDate.Group;
			this.table1.Add (this.lUpdateWithin);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.lUpdateWithin]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lupdatewithinEntry = new global::Gtk.Entry ();
			this.lupdatewithinEntry.Sensitive = false;
			this.lupdatewithinEntry.CanFocus = true;
			this.lupdatewithinEntry.Name = "lupdatewithinEntry";
			this.lupdatewithinEntry.IsEditable = true;
			this.lupdatewithinEntry.InvisibleChar = '•';
			this.table1.Add (this.lupdatewithinEntry);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.lupdatewithinEntry]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.nupdatedWithinEntry = new global::Gtk.Entry ();
			this.nupdatedWithinEntry.Sensitive = false;
			this.nupdatedWithinEntry.CanFocus = true;
			this.nupdatedWithinEntry.Name = "nupdatedWithinEntry";
			this.nupdatedWithinEntry.IsEditable = true;
			this.nupdatedWithinEntry.InvisibleChar = '•';
			this.table1.Add (this.nupdatedWithinEntry);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.nupdatedWithinEntry]));
			w9.TopAttach = ((uint)(2));
			w9.BottomAttach = ((uint)(3));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.nUpdateWithin = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Not updated within:"));
			this.nUpdateWithin.CanFocus = true;
			this.nUpdateWithin.Name = "nUpdateWithin";
			this.nUpdateWithin.DrawIndicator = true;
			this.nUpdateWithin.UseUnderline = true;
			this.nUpdateWithin.Group = this.lUpdateDate.Group;
			this.table1.Add (this.nUpdateWithin);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.nUpdateWithin]));
			w10.TopAttach = ((uint)(2));
			w10.BottomAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment2.Add (this.table1);
			this.updateFrame.Add (this.GtkAlignment2);
			this.vbox3.Add (this.updateFrame);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.updateFrame]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.GtkAlignment.Add (this.vbox3);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel4 = new global::Gtk.Label ();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Last Updated</b>");
			this.GtkLabel4.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel4;
			this.vbox2.Add (this.frame1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame1]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table (((uint)(2)), ((uint)(3)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.foundCheck = new global::Gtk.CheckButton ();
			this.foundCheck.CanFocus = true;
			this.foundCheck.Name = "foundCheck";
			this.foundCheck.Label = global::Mono.Unix.Catalog.GetString ("Last found by you");
			this.foundCheck.DrawIndicator = true;
			this.foundCheck.UseUnderline = true;
			this.table2.Add (this.foundCheck);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table2 [this.foundCheck]));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.foundCombo = global::Gtk.ComboBox.NewText ();
			this.foundCombo.AppendText (global::Mono.Unix.Catalog.GetString ("on:"));
			this.foundCombo.AppendText (global::Mono.Unix.Catalog.GetString ("on or after:"));
			this.foundCombo.AppendText (global::Mono.Unix.Catalog.GetString ("on or before:"));
			this.foundCombo.Sensitive = false;
			this.foundCombo.Name = "foundCombo";
			this.foundCombo.Active = 0;
			this.table2.Add (this.foundCombo);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table2 [this.foundCombo]));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.foundDateEntry = null;
			this.table2.Add (this.foundDateEntry);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table2 [this.foundDateEntry]));
			w19.LeftAttach = ((uint)(2));
			w19.RightAttach = ((uint)(3));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lFoundAnyOneCheck = new global::Gtk.CheckButton ();
			this.lFoundAnyOneCheck.CanFocus = true;
			this.lFoundAnyOneCheck.Name = "lFoundAnyOneCheck";
			this.lFoundAnyOneCheck.Label = global::Mono.Unix.Catalog.GetString ("Last found by anyone");
			this.lFoundAnyOneCheck.DrawIndicator = true;
			this.lFoundAnyOneCheck.UseUnderline = true;
			this.table2.Add (this.lFoundAnyOneCheck);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table2 [this.lFoundAnyOneCheck]));
			w20.TopAttach = ((uint)(1));
			w20.BottomAttach = ((uint)(2));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lFoundAnyoneCombo = global::Gtk.ComboBox.NewText ();
			this.lFoundAnyoneCombo.AppendText (global::Mono.Unix.Catalog.GetString ("On or before"));
			this.lFoundAnyoneCombo.AppendText (global::Mono.Unix.Catalog.GetString ("On or after"));
			this.lFoundAnyoneCombo.Sensitive = false;
			this.lFoundAnyoneCombo.Name = "lFoundAnyoneCombo";
			this.lFoundAnyoneCombo.Active = 0;
			this.table2.Add (this.lFoundAnyoneCombo);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table2 [this.lFoundAnyoneCombo]));
			w21.TopAttach = ((uint)(1));
			w21.BottomAttach = ((uint)(2));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lFoundAnyoneDate = null;
			this.table2.Add (this.lFoundAnyoneDate);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table2 [this.lFoundAnyoneDate]));
			w22.TopAttach = ((uint)(1));
			w22.BottomAttach = ((uint)(2));
			w22.LeftAttach = ((uint)(2));
			w22.RightAttach = ((uint)(3));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment1.Add (this.table2);
			this.frame2.Add (this.GtkAlignment1);
			this.GtkLabel7 = new global::Gtk.Label ();
			this.GtkLabel7.Name = "GtkLabel7";
			this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Last Found</b>");
			this.GtkLabel7.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel7;
			this.vbox2.Add (this.frame2);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame2]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.lastUpdateCheck.Toggled += new global::System.EventHandler (this.OnUpdateToggle);
			this.nUpdateWithin.Toggled += new global::System.EventHandler (this.OnNotWithinToggle);
			this.lUpdateWithin.Toggled += new global::System.EventHandler (this.OnLWithinToggle);
			this.lUpdateDate.Toggled += new global::System.EventHandler (this.OnLUpdateToggle);
			this.lFoundAnyOneCheck.Toggled += new global::System.EventHandler (this.OnLFoundAnyToggle);
			this.foundCheck.Toggled += new global::System.EventHandler (this.OnFoundCheckToggle);
		}
	}
}
