// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ocmgtk {
    
    
    public partial class OCMQueryPage2 {
        
        private Gtk.VBox vbox5;
        
        private Gtk.Frame frame4;
        
        private Gtk.Alignment GtkAlignment1;
        
        private Gtk.Table table1;
        
        private Gtk.RadioButton allContRadio;
        
        private Gtk.Frame contFrame;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.Table table2;
        
        private Gtk.CheckButton largeCheck;
        
        private Gtk.CheckButton microCheck;
        
        private Gtk.CheckButton notChosenCheck;
        
        private Gtk.CheckButton regularCheck;
        
        private Gtk.CheckButton smallCheck;
        
        private Gtk.CheckButton virtualCheck;
        
        private Gtk.RadioButton selRado;
        
        private Gtk.Label GtkLabel12;
        
        private Gtk.Frame frame5;
        
        private Gtk.Alignment GtkAlignment2;
        
        private Gtk.HBox hbox1;
        
        private Gtk.CheckButton descCheck;
        
        private Gtk.Entry descEntry;
        
        private Gtk.Label GtkLabel13;
        
        private Gtk.Frame frame7;
        
        private Gtk.Alignment GtkAlignment3;
        
        private Gtk.VBox vbox7;
        
        private Gtk.CheckButton markedCheck;
        
        private Gtk.Frame markFrame;
        
        private Gtk.Alignment GtkAlignment5;
        
        private Gtk.Table table3;
        
        private Gtk.RadioButton dnfRadio;
        
        private Gtk.RadioButton ftfRadio;
        
        private Gtk.RadioButton noDNFRadio;
        
        private Gtk.RadioButton noFTFRadio;
        
        private Gtk.CheckButton statusCheck;
        
        private Gtk.Frame statusFrame;
        
        private Gtk.Alignment GtkAlignment4;
        
        private Gtk.Table table4;
        
        private Gtk.CheckButton archiveCheck;
        
        private Gtk.CheckButton availCheck;
        
        private Gtk.CheckButton disabledCheck;
        
        private Gtk.CheckButton foundCheck;
        
        private Gtk.CheckButton mineCheck;
        
        private Gtk.CheckButton notFoundCheck;
        
        private Gtk.Label GtkLabel20;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ocmgtk.OCMQueryPage2
            Stetic.BinContainer.Attach(this);
            this.Name = "ocmgtk.OCMQueryPage2";
            // Container child ocmgtk.OCMQueryPage2.Gtk.Container+ContainerChild
            this.vbox5 = new Gtk.VBox();
            this.vbox5.Name = "vbox5";
            this.vbox5.Spacing = 6;
            this.vbox5.BorderWidth = ((uint)(6));
            // Container child vbox5.Gtk.Box+BoxChild
            this.frame4 = new Gtk.Frame();
            this.frame4.Name = "frame4";
            this.frame4.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame4.Gtk.Container+ContainerChild
            this.GtkAlignment1 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment1.Name = "GtkAlignment1";
            this.GtkAlignment1.LeftPadding = ((uint)(12));
            // Container child GtkAlignment1.Gtk.Container+ContainerChild
            this.table1 = new Gtk.Table(((uint)(3)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            this.table1.BorderWidth = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.allContRadio = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("Has any container size"));
            this.allContRadio.CanFocus = true;
            this.allContRadio.Name = "allContRadio";
            this.allContRadio.Active = true;
            this.allContRadio.DrawIndicator = true;
            this.allContRadio.UseUnderline = true;
            this.allContRadio.Group = new GLib.SList(System.IntPtr.Zero);
            this.table1.Add(this.allContRadio);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table1[this.allContRadio]));
            w1.XOptions = ((Gtk.AttachOptions)(4));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.contFrame = new Gtk.Frame();
            this.contFrame.Sensitive = false;
            this.contFrame.Name = "contFrame";
            // Container child contFrame.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.table2 = new Gtk.Table(((uint)(2)), ((uint)(3)), false);
            this.table2.Name = "table2";
            this.table2.RowSpacing = ((uint)(6));
            this.table2.ColumnSpacing = ((uint)(6));
            // Container child table2.Gtk.Table+TableChild
            this.largeCheck = new Gtk.CheckButton();
            this.largeCheck.CanFocus = true;
            this.largeCheck.Name = "largeCheck";
            this.largeCheck.Label = Mono.Unix.Catalog.GetString("Large");
            this.largeCheck.DrawIndicator = true;
            this.largeCheck.UseUnderline = true;
            this.table2.Add(this.largeCheck);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table2[this.largeCheck]));
            w2.TopAttach = ((uint)(1));
            w2.BottomAttach = ((uint)(2));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.microCheck = new Gtk.CheckButton();
            this.microCheck.CanFocus = true;
            this.microCheck.Name = "microCheck";
            this.microCheck.Label = Mono.Unix.Catalog.GetString("Micro");
            this.microCheck.DrawIndicator = true;
            this.microCheck.UseUnderline = true;
            this.table2.Add(this.microCheck);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table2[this.microCheck]));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.notChosenCheck = new Gtk.CheckButton();
            this.notChosenCheck.CanFocus = true;
            this.notChosenCheck.Name = "notChosenCheck";
            this.notChosenCheck.Label = Mono.Unix.Catalog.GetString("Not Chosen");
            this.notChosenCheck.DrawIndicator = true;
            this.notChosenCheck.UseUnderline = true;
            this.table2.Add(this.notChosenCheck);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table2[this.notChosenCheck]));
            w4.TopAttach = ((uint)(1));
            w4.BottomAttach = ((uint)(2));
            w4.LeftAttach = ((uint)(2));
            w4.RightAttach = ((uint)(3));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.regularCheck = new Gtk.CheckButton();
            this.regularCheck.CanFocus = true;
            this.regularCheck.Name = "regularCheck";
            this.regularCheck.Label = Mono.Unix.Catalog.GetString("Regular");
            this.regularCheck.DrawIndicator = true;
            this.regularCheck.UseUnderline = true;
            this.table2.Add(this.regularCheck);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table2[this.regularCheck]));
            w5.LeftAttach = ((uint)(2));
            w5.RightAttach = ((uint)(3));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.smallCheck = new Gtk.CheckButton();
            this.smallCheck.CanFocus = true;
            this.smallCheck.Name = "smallCheck";
            this.smallCheck.Label = Mono.Unix.Catalog.GetString("Small");
            this.smallCheck.DrawIndicator = true;
            this.smallCheck.UseUnderline = true;
            this.table2.Add(this.smallCheck);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table2[this.smallCheck]));
            w6.LeftAttach = ((uint)(1));
            w6.RightAttach = ((uint)(2));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.virtualCheck = new Gtk.CheckButton();
            this.virtualCheck.CanFocus = true;
            this.virtualCheck.Name = "virtualCheck";
            this.virtualCheck.Label = Mono.Unix.Catalog.GetString("Virtual");
            this.virtualCheck.DrawIndicator = true;
            this.virtualCheck.UseUnderline = true;
            this.table2.Add(this.virtualCheck);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table2[this.virtualCheck]));
            w7.TopAttach = ((uint)(1));
            w7.BottomAttach = ((uint)(2));
            w7.LeftAttach = ((uint)(1));
            w7.RightAttach = ((uint)(2));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment.Add(this.table2);
            this.contFrame.Add(this.GtkAlignment);
            this.table1.Add(this.contFrame);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table1[this.contFrame]));
            w10.TopAttach = ((uint)(2));
            w10.BottomAttach = ((uint)(3));
            w10.RightAttach = ((uint)(2));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.selRado = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("Has any of the following sizes:"));
            this.selRado.CanFocus = true;
            this.selRado.Name = "selRado";
            this.selRado.DrawIndicator = true;
            this.selRado.UseUnderline = true;
            this.selRado.Group = this.allContRadio.Group;
            this.table1.Add(this.selRado);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table1[this.selRado]));
            w11.TopAttach = ((uint)(1));
            w11.BottomAttach = ((uint)(2));
            w11.XOptions = ((Gtk.AttachOptions)(4));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment1.Add(this.table1);
            this.frame4.Add(this.GtkAlignment1);
            this.GtkLabel12 = new Gtk.Label();
            this.GtkLabel12.Name = "GtkLabel12";
            this.GtkLabel12.LabelProp = Mono.Unix.Catalog.GetString("<b>Container Type</b>");
            this.GtkLabel12.UseMarkup = true;
            this.frame4.LabelWidget = this.GtkLabel12;
            this.vbox5.Add(this.frame4);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.vbox5[this.frame4]));
            w14.Position = 0;
            w14.Expand = false;
            w14.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.frame5 = new Gtk.Frame();
            this.frame5.Name = "frame5";
            this.frame5.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame5.Gtk.Container+ContainerChild
            this.GtkAlignment2 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment2.Name = "GtkAlignment2";
            this.GtkAlignment2.LeftPadding = ((uint)(12));
            // Container child GtkAlignment2.Gtk.Container+ContainerChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.descCheck = new Gtk.CheckButton();
            this.descCheck.CanFocus = true;
            this.descCheck.Name = "descCheck";
            this.descCheck.Label = Mono.Unix.Catalog.GetString("Description contains the following words:");
            this.descCheck.DrawIndicator = true;
            this.descCheck.UseUnderline = true;
            this.hbox1.Add(this.descCheck);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbox1[this.descCheck]));
            w15.Position = 0;
            w15.Expand = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.descEntry = new Gtk.Entry();
            this.descEntry.Sensitive = false;
            this.descEntry.CanFocus = true;
            this.descEntry.Name = "descEntry";
            this.descEntry.IsEditable = true;
            this.descEntry.InvisibleChar = '•';
            this.hbox1.Add(this.descEntry);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.hbox1[this.descEntry]));
            w16.Position = 1;
            this.GtkAlignment2.Add(this.hbox1);
            this.frame5.Add(this.GtkAlignment2);
            this.GtkLabel13 = new Gtk.Label();
            this.GtkLabel13.Name = "GtkLabel13";
            this.GtkLabel13.LabelProp = Mono.Unix.Catalog.GetString("<b>Cache Description</b>");
            this.GtkLabel13.UseMarkup = true;
            this.frame5.LabelWidget = this.GtkLabel13;
            this.vbox5.Add(this.frame5);
            Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.vbox5[this.frame5]));
            w19.Position = 1;
            w19.Expand = false;
            w19.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.frame7 = new Gtk.Frame();
            this.frame7.Name = "frame7";
            this.frame7.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame7.Gtk.Container+ContainerChild
            this.GtkAlignment3 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment3.Name = "GtkAlignment3";
            this.GtkAlignment3.LeftPadding = ((uint)(12));
            // Container child GtkAlignment3.Gtk.Container+ContainerChild
            this.vbox7 = new Gtk.VBox();
            this.vbox7.Name = "vbox7";
            this.vbox7.Spacing = 6;
            // Container child vbox7.Gtk.Box+BoxChild
            this.markedCheck = new Gtk.CheckButton();
            this.markedCheck.CanFocus = true;
            this.markedCheck.Name = "markedCheck";
            this.markedCheck.Label = Mono.Unix.Catalog.GetString("Only caches that are marked:");
            this.markedCheck.DrawIndicator = true;
            this.markedCheck.UseUnderline = true;
            this.vbox7.Add(this.markedCheck);
            Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.vbox7[this.markedCheck]));
            w20.Position = 0;
            w20.Expand = false;
            w20.Fill = false;
            // Container child vbox7.Gtk.Box+BoxChild
            this.markFrame = new Gtk.Frame();
            this.markFrame.Sensitive = false;
            this.markFrame.Name = "markFrame";
            this.markFrame.ShadowType = ((Gtk.ShadowType)(1));
            // Container child markFrame.Gtk.Container+ContainerChild
            this.GtkAlignment5 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment5.Name = "GtkAlignment5";
            this.GtkAlignment5.LeftPadding = ((uint)(12));
            // Container child GtkAlignment5.Gtk.Container+ContainerChild
            this.table3 = new Gtk.Table(((uint)(2)), ((uint)(3)), false);
            this.table3.Name = "table3";
            this.table3.RowSpacing = ((uint)(6));
            this.table3.ColumnSpacing = ((uint)(6));
            // Container child table3.Gtk.Table+TableChild
            this.dnfRadio = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("Didn't Find It"));
            this.dnfRadio.CanFocus = true;
            this.dnfRadio.Name = "dnfRadio";
            this.dnfRadio.Active = true;
            this.dnfRadio.DrawIndicator = true;
            this.dnfRadio.UseUnderline = true;
            this.dnfRadio.Group = new GLib.SList(System.IntPtr.Zero);
            this.table3.Add(this.dnfRadio);
            Gtk.Table.TableChild w21 = ((Gtk.Table.TableChild)(this.table3[this.dnfRadio]));
            w21.TopAttach = ((uint)(1));
            w21.BottomAttach = ((uint)(2));
            w21.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.ftfRadio = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("First to Find"));
            this.ftfRadio.CanFocus = true;
            this.ftfRadio.Name = "ftfRadio";
            this.ftfRadio.DrawIndicator = true;
            this.ftfRadio.UseUnderline = true;
            this.ftfRadio.Group = this.dnfRadio.Group;
            this.table3.Add(this.ftfRadio);
            Gtk.Table.TableChild w22 = ((Gtk.Table.TableChild)(this.table3[this.ftfRadio]));
            w22.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.noDNFRadio = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("Not Didn't Find It"));
            this.noDNFRadio.CanFocus = true;
            this.noDNFRadio.Name = "noDNFRadio";
            this.noDNFRadio.DrawIndicator = true;
            this.noDNFRadio.UseUnderline = true;
            this.noDNFRadio.Group = this.dnfRadio.Group;
            this.table3.Add(this.noDNFRadio);
            Gtk.Table.TableChild w23 = ((Gtk.Table.TableChild)(this.table3[this.noDNFRadio]));
            w23.TopAttach = ((uint)(1));
            w23.BottomAttach = ((uint)(2));
            w23.LeftAttach = ((uint)(1));
            w23.RightAttach = ((uint)(2));
            w23.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.noFTFRadio = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("Not First to Find"));
            this.noFTFRadio.CanFocus = true;
            this.noFTFRadio.Name = "noFTFRadio";
            this.noFTFRadio.DrawIndicator = true;
            this.noFTFRadio.UseUnderline = true;
            this.noFTFRadio.Group = this.dnfRadio.Group;
            this.table3.Add(this.noFTFRadio);
            Gtk.Table.TableChild w24 = ((Gtk.Table.TableChild)(this.table3[this.noFTFRadio]));
            w24.LeftAttach = ((uint)(1));
            w24.RightAttach = ((uint)(2));
            w24.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment5.Add(this.table3);
            this.markFrame.Add(this.GtkAlignment5);
            this.vbox7.Add(this.markFrame);
            Gtk.Box.BoxChild w27 = ((Gtk.Box.BoxChild)(this.vbox7[this.markFrame]));
            w27.Position = 1;
            w27.Expand = false;
            // Container child vbox7.Gtk.Box+BoxChild
            this.statusCheck = new Gtk.CheckButton();
            this.statusCheck.CanFocus = true;
            this.statusCheck.Name = "statusCheck";
            this.statusCheck.Label = Mono.Unix.Catalog.GetString("Caches with the following status flags:");
            this.statusCheck.DrawIndicator = true;
            this.statusCheck.UseUnderline = true;
            this.vbox7.Add(this.statusCheck);
            Gtk.Box.BoxChild w28 = ((Gtk.Box.BoxChild)(this.vbox7[this.statusCheck]));
            w28.Position = 2;
            w28.Expand = false;
            w28.Fill = false;
            // Container child vbox7.Gtk.Box+BoxChild
            this.statusFrame = new Gtk.Frame();
            this.statusFrame.Sensitive = false;
            this.statusFrame.Name = "statusFrame";
            this.statusFrame.ShadowType = ((Gtk.ShadowType)(1));
            // Container child statusFrame.Gtk.Container+ContainerChild
            this.GtkAlignment4 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment4.Name = "GtkAlignment4";
            this.GtkAlignment4.LeftPadding = ((uint)(12));
            // Container child GtkAlignment4.Gtk.Container+ContainerChild
            this.table4 = new Gtk.Table(((uint)(2)), ((uint)(4)), false);
            this.table4.Name = "table4";
            this.table4.RowSpacing = ((uint)(6));
            this.table4.ColumnSpacing = ((uint)(6));
            // Container child table4.Gtk.Table+TableChild
            this.archiveCheck = new Gtk.CheckButton();
            this.archiveCheck.CanFocus = true;
            this.archiveCheck.Name = "archiveCheck";
            this.archiveCheck.Label = Mono.Unix.Catalog.GetString("Archived");
            this.archiveCheck.Active = true;
            this.archiveCheck.DrawIndicator = true;
            this.archiveCheck.UseUnderline = true;
            this.table4.Add(this.archiveCheck);
            Gtk.Table.TableChild w29 = ((Gtk.Table.TableChild)(this.table4[this.archiveCheck]));
            w29.TopAttach = ((uint)(1));
            w29.BottomAttach = ((uint)(2));
            w29.LeftAttach = ((uint)(2));
            w29.RightAttach = ((uint)(3));
            w29.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.availCheck = new Gtk.CheckButton();
            this.availCheck.CanFocus = true;
            this.availCheck.Name = "availCheck";
            this.availCheck.Label = Mono.Unix.Catalog.GetString("Available");
            this.availCheck.Active = true;
            this.availCheck.DrawIndicator = true;
            this.availCheck.UseUnderline = true;
            this.table4.Add(this.availCheck);
            Gtk.Table.TableChild w30 = ((Gtk.Table.TableChild)(this.table4[this.availCheck]));
            w30.TopAttach = ((uint)(1));
            w30.BottomAttach = ((uint)(2));
            w30.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.disabledCheck = new Gtk.CheckButton();
            this.disabledCheck.CanFocus = true;
            this.disabledCheck.Name = "disabledCheck";
            this.disabledCheck.Label = Mono.Unix.Catalog.GetString("Disabled");
            this.disabledCheck.Active = true;
            this.disabledCheck.DrawIndicator = true;
            this.disabledCheck.UseUnderline = true;
            this.table4.Add(this.disabledCheck);
            Gtk.Table.TableChild w31 = ((Gtk.Table.TableChild)(this.table4[this.disabledCheck]));
            w31.TopAttach = ((uint)(1));
            w31.BottomAttach = ((uint)(2));
            w31.LeftAttach = ((uint)(1));
            w31.RightAttach = ((uint)(2));
            w31.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.foundCheck = new Gtk.CheckButton();
            this.foundCheck.CanFocus = true;
            this.foundCheck.Name = "foundCheck";
            this.foundCheck.Label = Mono.Unix.Catalog.GetString("Found");
            this.foundCheck.Active = true;
            this.foundCheck.DrawIndicator = true;
            this.foundCheck.UseUnderline = true;
            this.table4.Add(this.foundCheck);
            Gtk.Table.TableChild w32 = ((Gtk.Table.TableChild)(this.table4[this.foundCheck]));
            w32.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.mineCheck = new Gtk.CheckButton();
            this.mineCheck.CanFocus = true;
            this.mineCheck.Name = "mineCheck";
            this.mineCheck.Label = Mono.Unix.Catalog.GetString("Mine");
            this.mineCheck.Active = true;
            this.mineCheck.DrawIndicator = true;
            this.mineCheck.UseUnderline = true;
            this.table4.Add(this.mineCheck);
            Gtk.Table.TableChild w33 = ((Gtk.Table.TableChild)(this.table4[this.mineCheck]));
            w33.LeftAttach = ((uint)(2));
            w33.RightAttach = ((uint)(3));
            w33.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.notFoundCheck = new Gtk.CheckButton();
            this.notFoundCheck.CanFocus = true;
            this.notFoundCheck.Name = "notFoundCheck";
            this.notFoundCheck.Label = Mono.Unix.Catalog.GetString("Not Found");
            this.notFoundCheck.Active = true;
            this.notFoundCheck.DrawIndicator = true;
            this.notFoundCheck.UseUnderline = true;
            this.table4.Add(this.notFoundCheck);
            Gtk.Table.TableChild w34 = ((Gtk.Table.TableChild)(this.table4[this.notFoundCheck]));
            w34.LeftAttach = ((uint)(1));
            w34.RightAttach = ((uint)(2));
            w34.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment4.Add(this.table4);
            this.statusFrame.Add(this.GtkAlignment4);
            this.vbox7.Add(this.statusFrame);
            Gtk.Box.BoxChild w37 = ((Gtk.Box.BoxChild)(this.vbox7[this.statusFrame]));
            w37.Position = 3;
            w37.Expand = false;
            this.GtkAlignment3.Add(this.vbox7);
            this.frame7.Add(this.GtkAlignment3);
            this.GtkLabel20 = new Gtk.Label();
            this.GtkLabel20.Name = "GtkLabel20";
            this.GtkLabel20.LabelProp = Mono.Unix.Catalog.GetString("<b>Cache Status</b>");
            this.GtkLabel20.UseMarkup = true;
            this.frame7.LabelWidget = this.GtkLabel20;
            this.vbox5.Add(this.frame7);
            Gtk.Box.BoxChild w40 = ((Gtk.Box.BoxChild)(this.vbox5[this.frame7]));
            w40.Position = 2;
            w40.Expand = false;
            w40.Fill = false;
            this.Add(this.vbox5);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
            this.allContRadio.Toggled += new System.EventHandler(this.OnAnyToggle);
            this.descCheck.Toggled += new System.EventHandler(this.OnDescToggled);
            this.markedCheck.Toggled += new System.EventHandler(this.OnMarkedtoggle);
            this.statusCheck.Toggled += new System.EventHandler(this.OnStatusToggle);
        }
    }
}
