
// This file has been generated by the GUI designer. Do not modify.
namespace ocmgtk
{
	public partial class AttributeFilterWidget
	{
		private global::Gtk.EventBox eventbox1;
		
		private global::Gtk.Image attrIcon;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ocmgtk.AttributeFilterWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "ocmgtk.AttributeFilterWidget";
			// Container child ocmgtk.AttributeFilterWidget.Gtk.Container+ContainerChild
			this.eventbox1 = new global::Gtk.EventBox ();
			this.eventbox1.Name = "eventbox1";
			// Container child eventbox1.Gtk.Container+ContainerChild
			this.attrIcon = new global::Gtk.Image ();
			this.attrIcon.Name = "attrIcon";
			this.eventbox1.Add (this.attrIcon);
			this.Add (this.eventbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.eventbox1.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnPress);
			this.eventbox1.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnRelease);
			this.attrIcon.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnRelease);
		}
	}
}
