
// This file has been generated by the GUI designer. Do not modify.
namespace ocmgtk
{
	public partial class LoadGPSFieldNotes
	{
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Image image38;
		
		private global::Gtk.Label logText;
		
		private global::Gtk.HSeparator hseparator3;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label lastScan;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label lastScanTD;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.CheckButton checkIgnoreLogs;
		
		private global::ocmgtk.DateWidget ignoreDate;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ocmgtk.LoadGPSFieldNotes
			this.WidthRequest = 550;
			this.Name = "ocmgtk.LoadGPSFieldNotes";
			this.Title = global::Mono.Unix.Catalog.GetString ("Receive Field Notes...");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.BorderWidth = ((uint)(6));
			this.Resizable = false;
			this.AllowGrow = false;
			this.SkipPagerHint = true;
			this.SkipTaskbarHint = true;
			// Internal child ocmgtk.LoadGPSFieldNotes.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.Spacing = 6;
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.image38 = new global::Gtk.Image ();
			this.image38.Name = "image38";
			this.image38.Yalign = 0F;
			this.image38.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-info", global::Gtk.IconSize.Dialog);
			this.hbox3.Add (this.image38);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.image38]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.logText = new global::Gtk.Label ();
			this.logText.Name = "logText";
			this.logText.LabelProp = global::Mono.Unix.Catalog.GetString ("The field notes file from your GPS will be scanned and OCM will automatically update your caches based on the field notes file. \n\nIf you wish to work with the comments entered in the field before logging your finds online, go to <b>View → Field Notes...</b>");
			this.logText.UseMarkup = true;
			this.logText.Wrap = true;
			this.logText.WidthChars = 60;
			this.hbox3.Add (this.logText);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.logText]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			w1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox3]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.Name = "hseparator3";
			w1.Add (this.hseparator3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1 [this.hseparator3]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Last field notes scan:</b>");
			this.label1.UseMarkup = true;
			this.hbox5.Add (this.label1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.lastScan = new global::Gtk.Label ();
			this.lastScan.Name = "lastScan";
			this.lastScan.LabelProp = global::Mono.Unix.Catalog.GetString ("label3");
			this.hbox5.Add (this.lastScan);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.lastScan]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			w1.Add (this.hbox5);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox5]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Last field notes scan from this device:</b>");
			this.label2.UseMarkup = true;
			this.hbox6.Add (this.label2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label2]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.lastScanTD = new global::Gtk.Label ();
			this.lastScanTD.Name = "lastScanTD";
			this.lastScanTD.LabelProp = global::Mono.Unix.Catalog.GetString ("label4");
			this.hbox6.Add (this.lastScanTD);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.lastScanTD]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			w1.Add (this.hbox6);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox6]));
			w11.Position = 3;
			w11.Expand = false;
			w11.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			w1.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(w1 [this.hseparator1]));
			w12.Position = 4;
			w12.Expand = false;
			w12.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.checkIgnoreLogs = new global::Gtk.CheckButton ();
			this.checkIgnoreLogs.CanFocus = true;
			this.checkIgnoreLogs.Name = "checkIgnoreLogs";
			this.checkIgnoreLogs.Label = global::Mono.Unix.Catalog.GetString ("Ignore logs before:");
			this.checkIgnoreLogs.DrawIndicator = true;
			this.checkIgnoreLogs.UseUnderline = true;
			this.hbox4.Add (this.checkIgnoreLogs);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.checkIgnoreLogs]));
			w13.Position = 0;
			w13.Expand = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.ignoreDate = null;
			this.hbox4.Add (this.ignoreDate);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.ignoreDate]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			w1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox4]));
			w15.Position = 5;
			w15.Expand = false;
			w15.Fill = false;
			// Internal child ocmgtk.LoadGPSFieldNotes.ActionArea
			global::Gtk.HButtonBox w16 = this.ActionArea;
			w16.Name = "dialog1_ActionArea";
			w16.Spacing = 10;
			w16.BorderWidth = ((uint)(5));
			w16.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w17 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w16 [this.buttonCancel]));
			w17.Expand = false;
			w17.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w18 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w16 [this.buttonOk]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 562;
			this.DefaultHeight = 285;
			this.buttonOk.HasDefault = true;
			this.Show ();
		}
	}
}
