// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ocmgtk {
    
    
    public partial class CleanUpPage1 {
        
        private Gtk.VBox vbox1;
        
        private Gtk.Label label2;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ocmgtk.CleanUpPage1
            Stetic.BinContainer.Attach(this);
            this.Name = "ocmgtk.CleanUpPage1";
            // Container child ocmgtk.CleanUpPage1.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.Ypad = 15;
            this.label2.Xalign = 0F;
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("This assistant will help guide you through cleaning up your OCM database.\n\nBy reducing the number of logs per cache and compacting your database, you can greatly reduce the size of you OCM database which will improve performance. ");
            this.label2.Wrap = true;
            this.label2.WidthChars = 80;
            this.vbox1.Add(this.label2);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox1[this.label2]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
