
// This file has been generated by the GUI designer. Do not modify.
namespace ocmgtk
{
	public partial class SetupAssistantPage4
	{
		private global::Gtk.Label label2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ocmgtk.SetupAssistantPage4
			global::Stetic.BinContainer.Attach (this);
			this.Name = "ocmgtk.SetupAssistantPage4";
			// Container child ocmgtk.SetupAssistantPage4.Gtk.Container+ContainerChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xpad = 6;
			this.label2.Ypad = 6;
			this.label2.Yalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("OCM Is now ready to use. Click Close to close this assistant and begin using OCM.\n\nYou will need to use a GPX or LOC file to populate the OCM database with caches. In Geocaching.com you can build a Pocket Query if you are a Premium Member. For Terraching, go to the \"To Do List\" on Terracaching.com. For Navicache, create an advanced search and download the caches from \"My NaviCache\". You can find links to all of these under the Web menu.\n\nVisit the OCM wiki for help and how to guides by click on Help>OCM Wiki...\n");
			this.label2.Wrap = true;
			this.label2.WidthChars = 60;
			this.Add (this.label2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
