// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ocmgtk {
    
    
    public partial class MapSelectionWidget {
        
        private Gtk.Table table6;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Image image17;
        
        private Gtk.Label label1;
        
        private Gtk.ScrolledWindow scrolledwindow1;
        
        private Gtk.TreeView mapView;
        
        private Gtk.Table table7;
        
        private Gtk.Button activateButton;
        
        private Gtk.Button deactivateButton;
        
        private Gtk.Button deleteButton;
        
        private Gtk.Button downButton;
        
        private Gtk.HSeparator hseparator1;
        
        private Gtk.HSeparator hseparator2;
        
        private Gtk.HSeparator hseparator3;
        
        private Gtk.Button openButton;
        
        private Gtk.Button restoreButton;
        
        private Gtk.Button upButton;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ocmgtk.MapSelectionWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "ocmgtk.MapSelectionWidget";
            // Container child ocmgtk.MapSelectionWidget.Gtk.Container+ContainerChild
            this.table6 = new Gtk.Table(((uint)(2)), ((uint)(2)), false);
            this.table6.Name = "table6";
            this.table6.RowSpacing = ((uint)(6));
            this.table6.ColumnSpacing = ((uint)(6));
            this.table6.BorderWidth = ((uint)(6));
            // Container child table6.Gtk.Table+TableChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.image17 = new Gtk.Image();
            this.image17.Name = "image17";
            this.image17.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-dialog-info", Gtk.IconSize.Button, 20);
            this.hbox1.Add(this.image17);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox1[this.image17]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.Xalign = 0F;
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("The highest map in the list will be the default map when OCM starts.");
            this.hbox1.Add(this.label1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.label1]));
            w2.Position = 1;
            this.table6.Add(this.hbox1);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table6[this.hbox1]));
            w3.RightAttach = ((uint)(2));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table6.Gtk.Table+TableChild
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow1.Gtk.Container+ContainerChild
            this.mapView = new Gtk.TreeView();
            this.mapView.CanFocus = true;
            this.mapView.Name = "mapView";
            this.scrolledwindow1.Add(this.mapView);
            this.table6.Add(this.scrolledwindow1);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table6[this.scrolledwindow1]));
            w5.TopAttach = ((uint)(1));
            w5.BottomAttach = ((uint)(2));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table6.Gtk.Table+TableChild
            this.table7 = new Gtk.Table(((uint)(11)), ((uint)(1)), false);
            this.table7.Name = "table7";
            this.table7.RowSpacing = ((uint)(6));
            this.table7.ColumnSpacing = ((uint)(6));
            // Container child table7.Gtk.Table+TableChild
            this.activateButton = new Gtk.Button();
            this.activateButton.Sensitive = false;
            this.activateButton.CanFocus = true;
            this.activateButton.Name = "activateButton";
            this.activateButton.UseUnderline = true;
            // Container child activateButton.Gtk.Container+ContainerChild
            Gtk.Alignment w6 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w7 = new Gtk.HBox();
            w7.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w8 = new Gtk.Image();
            w8.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-apply", Gtk.IconSize.Menu, 16);
            w7.Add(w8);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w10 = new Gtk.Label();
            w10.LabelProp = Mono.Unix.Catalog.GetString("Enable Map");
            w10.UseUnderline = true;
            w7.Add(w10);
            w6.Add(w7);
            this.activateButton.Add(w6);
            this.table7.Add(this.activateButton);
            Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table7[this.activateButton]));
            w14.TopAttach = ((uint)(4));
            w14.BottomAttach = ((uint)(5));
            w14.XOptions = ((Gtk.AttachOptions)(4));
            w14.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table7.Gtk.Table+TableChild
            this.deactivateButton = new Gtk.Button();
            this.deactivateButton.Sensitive = false;
            this.deactivateButton.CanFocus = true;
            this.deactivateButton.Name = "deactivateButton";
            this.deactivateButton.UseUnderline = true;
            // Container child deactivateButton.Gtk.Container+ContainerChild
            Gtk.Alignment w15 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w16 = new Gtk.HBox();
            w16.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w17 = new Gtk.Image();
            w17.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-cancel", Gtk.IconSize.Menu, 16);
            w16.Add(w17);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w19 = new Gtk.Label();
            w19.LabelProp = Mono.Unix.Catalog.GetString("Disable Map");
            w19.UseUnderline = true;
            w16.Add(w19);
            w15.Add(w16);
            this.deactivateButton.Add(w15);
            this.table7.Add(this.deactivateButton);
            Gtk.Table.TableChild w23 = ((Gtk.Table.TableChild)(this.table7[this.deactivateButton]));
            w23.TopAttach = ((uint)(5));
            w23.BottomAttach = ((uint)(6));
            w23.XOptions = ((Gtk.AttachOptions)(4));
            w23.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table7.Gtk.Table+TableChild
            this.deleteButton = new Gtk.Button();
            this.deleteButton.Sensitive = false;
            this.deleteButton.CanFocus = true;
            this.deleteButton.Name = "deleteButton";
            this.deleteButton.UseUnderline = true;
            // Container child deleteButton.Gtk.Container+ContainerChild
            Gtk.Alignment w24 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w25 = new Gtk.HBox();
            w25.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w26 = new Gtk.Image();
            w26.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-delete", Gtk.IconSize.Menu, 16);
            w25.Add(w26);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w28 = new Gtk.Label();
            w28.LabelProp = Mono.Unix.Catalog.GetString("Delete Map");
            w28.UseUnderline = true;
            w25.Add(w28);
            w24.Add(w25);
            this.deleteButton.Add(w24);
            this.table7.Add(this.deleteButton);
            Gtk.Table.TableChild w32 = ((Gtk.Table.TableChild)(this.table7[this.deleteButton]));
            w32.TopAttach = ((uint)(6));
            w32.BottomAttach = ((uint)(7));
            w32.XOptions = ((Gtk.AttachOptions)(4));
            w32.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table7.Gtk.Table+TableChild
            this.downButton = new Gtk.Button();
            this.downButton.Sensitive = false;
            this.downButton.CanFocus = true;
            this.downButton.Name = "downButton";
            this.downButton.UseUnderline = true;
            // Container child downButton.Gtk.Container+ContainerChild
            Gtk.Alignment w33 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w34 = new Gtk.HBox();
            w34.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w35 = new Gtk.Image();
            w35.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-go-down", Gtk.IconSize.Menu, 16);
            w34.Add(w35);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w37 = new Gtk.Label();
            w37.LabelProp = Mono.Unix.Catalog.GetString("Move Down");
            w37.UseUnderline = true;
            w34.Add(w37);
            w33.Add(w34);
            this.downButton.Add(w33);
            this.table7.Add(this.downButton);
            Gtk.Table.TableChild w41 = ((Gtk.Table.TableChild)(this.table7[this.downButton]));
            w41.TopAttach = ((uint)(2));
            w41.BottomAttach = ((uint)(3));
            w41.XOptions = ((Gtk.AttachOptions)(4));
            w41.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table7.Gtk.Table+TableChild
            this.hseparator1 = new Gtk.HSeparator();
            this.hseparator1.Name = "hseparator1";
            this.table7.Add(this.hseparator1);
            Gtk.Table.TableChild w42 = ((Gtk.Table.TableChild)(this.table7[this.hseparator1]));
            w42.TopAttach = ((uint)(3));
            w42.BottomAttach = ((uint)(4));
            w42.XOptions = ((Gtk.AttachOptions)(4));
            w42.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table7.Gtk.Table+TableChild
            this.hseparator2 = new Gtk.HSeparator();
            this.hseparator2.Name = "hseparator2";
            this.table7.Add(this.hseparator2);
            Gtk.Table.TableChild w43 = ((Gtk.Table.TableChild)(this.table7[this.hseparator2]));
            w43.XOptions = ((Gtk.AttachOptions)(4));
            w43.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table7.Gtk.Table+TableChild
            this.hseparator3 = new Gtk.HSeparator();
            this.hseparator3.Name = "hseparator3";
            this.table7.Add(this.hseparator3);
            Gtk.Table.TableChild w44 = ((Gtk.Table.TableChild)(this.table7[this.hseparator3]));
            w44.TopAttach = ((uint)(7));
            w44.BottomAttach = ((uint)(8));
            w44.XOptions = ((Gtk.AttachOptions)(4));
            w44.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table7.Gtk.Table+TableChild
            this.openButton = new Gtk.Button();
            this.openButton.CanFocus = true;
            this.openButton.Name = "openButton";
            this.openButton.UseUnderline = true;
            // Container child openButton.Gtk.Container+ContainerChild
            Gtk.Alignment w45 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w46 = new Gtk.HBox();
            w46.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w47 = new Gtk.Image();
            w47.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-open", Gtk.IconSize.Menu, 16);
            w46.Add(w47);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w49 = new Gtk.Label();
            w49.LabelProp = Mono.Unix.Catalog.GetString("Import Map File");
            w49.UseUnderline = true;
            w46.Add(w49);
            w45.Add(w46);
            this.openButton.Add(w45);
            this.table7.Add(this.openButton);
            Gtk.Table.TableChild w53 = ((Gtk.Table.TableChild)(this.table7[this.openButton]));
            w53.TopAttach = ((uint)(9));
            w53.BottomAttach = ((uint)(11));
            w53.XOptions = ((Gtk.AttachOptions)(4));
            w53.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table7.Gtk.Table+TableChild
            this.restoreButton = new Gtk.Button();
            this.restoreButton.CanFocus = true;
            this.restoreButton.Name = "restoreButton";
            this.restoreButton.UseUnderline = true;
            // Container child restoreButton.Gtk.Container+ContainerChild
            Gtk.Alignment w54 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w55 = new Gtk.HBox();
            w55.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w56 = new Gtk.Image();
            w56.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-clear", Gtk.IconSize.Menu, 16);
            w55.Add(w56);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w58 = new Gtk.Label();
            w58.LabelProp = Mono.Unix.Catalog.GetString("Restore Defaults");
            w58.UseUnderline = true;
            w55.Add(w58);
            w54.Add(w55);
            this.restoreButton.Add(w54);
            this.table7.Add(this.restoreButton);
            Gtk.Table.TableChild w62 = ((Gtk.Table.TableChild)(this.table7[this.restoreButton]));
            w62.TopAttach = ((uint)(8));
            w62.BottomAttach = ((uint)(9));
            w62.XOptions = ((Gtk.AttachOptions)(4));
            w62.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table7.Gtk.Table+TableChild
            this.upButton = new Gtk.Button();
            this.upButton.Sensitive = false;
            this.upButton.CanFocus = true;
            this.upButton.Name = "upButton";
            this.upButton.UseUnderline = true;
            // Container child upButton.Gtk.Container+ContainerChild
            Gtk.Alignment w63 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w64 = new Gtk.HBox();
            w64.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w65 = new Gtk.Image();
            w65.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-go-up", Gtk.IconSize.Menu, 16);
            w64.Add(w65);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w67 = new Gtk.Label();
            w67.LabelProp = Mono.Unix.Catalog.GetString("Move Up");
            w67.UseUnderline = true;
            w64.Add(w67);
            w63.Add(w64);
            this.upButton.Add(w63);
            this.table7.Add(this.upButton);
            Gtk.Table.TableChild w71 = ((Gtk.Table.TableChild)(this.table7[this.upButton]));
            w71.TopAttach = ((uint)(1));
            w71.BottomAttach = ((uint)(2));
            w71.XOptions = ((Gtk.AttachOptions)(4));
            w71.YOptions = ((Gtk.AttachOptions)(4));
            this.table6.Add(this.table7);
            Gtk.Table.TableChild w72 = ((Gtk.Table.TableChild)(this.table6[this.table7]));
            w72.TopAttach = ((uint)(1));
            w72.BottomAttach = ((uint)(2));
            w72.LeftAttach = ((uint)(1));
            w72.RightAttach = ((uint)(2));
            w72.XOptions = ((Gtk.AttachOptions)(4));
            w72.YOptions = ((Gtk.AttachOptions)(4));
            this.Add(this.table6);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
            this.upButton.Clicked += new System.EventHandler(this.OnUpButtonClicked);
            this.restoreButton.Clicked += new System.EventHandler(this.OnRestoreButtonClicked);
            this.openButton.Clicked += new System.EventHandler(this.OnOpenButtonClicked);
            this.downButton.Clicked += new System.EventHandler(this.OnDownButtonClicked);
            this.deleteButton.Clicked += new System.EventHandler(this.OnDeleteButtonClicked);
            this.deactivateButton.Clicked += new System.EventHandler(this.OnDeactivateButtonClicked);
            this.activateButton.Clicked += new System.EventHandler(this.OnActivateButtonClicked);
        }
    }
}
