
// This file has been generated by the GUI designer. Do not modify.
namespace ocmgtk
{
	public partial class CacheInfoWidget
	{
		private global::Gtk.Notebook infoNoteBook;
		
		private global::ocmgtk.GeocacheInfoPanel quickInfoPane;
		
		private global::Gtk.Label quickInfoLabel;
		
		private global::ocmgtk.DescriptionWidget descriptionPane;
		
		private global::Gtk.Label descriptionTab;
		
		private global::ocmgtk.LogViewerWidget logViewer;
		
		private global::Gtk.Label logLabel;
		
		private global::ocmgtk.WaypointWidget waypointWidget;
		
		private global::Gtk.Label waypointLabel;
		
		private global::ocmgtk.NotesWidget cacheNotes;
		
		private global::Gtk.Label notesLabel;
		
		private global::ocmgtk.ImagesWidget imageWidget;
		
		private global::Gtk.Label imageLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ocmgtk.CacheInfoWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "ocmgtk.CacheInfoWidget";
			// Container child ocmgtk.CacheInfoWidget.Gtk.Container+ContainerChild
			this.infoNoteBook = new global::Gtk.Notebook ();
			this.infoNoteBook.CanFocus = true;
			this.infoNoteBook.Name = "infoNoteBook";
			this.infoNoteBook.CurrentPage = 5;
			// Container child infoNoteBook.Gtk.Notebook+NotebookChild
			this.quickInfoPane = null;
			this.infoNoteBook.Add (this.quickInfoPane);
			// Notebook tab
			this.quickInfoLabel = new global::Gtk.Label ();
			this.quickInfoLabel.Name = "quickInfoLabel";
			this.quickInfoLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Quick Info");
			this.infoNoteBook.SetTabLabel (this.quickInfoPane, this.quickInfoLabel);
			this.quickInfoLabel.ShowAll ();
			// Container child infoNoteBook.Gtk.Notebook+NotebookChild
			this.descriptionPane = null;
			this.infoNoteBook.Add (this.descriptionPane);
			global::Gtk.Notebook.NotebookChild w2 = ((global::Gtk.Notebook.NotebookChild)(this.infoNoteBook [this.descriptionPane]));
			w2.Position = 1;
			// Notebook tab
			this.descriptionTab = new global::Gtk.Label ();
			this.descriptionTab.Name = "descriptionTab";
			this.descriptionTab.LabelProp = global::Mono.Unix.Catalog.GetString ("Description");
			this.infoNoteBook.SetTabLabel (this.descriptionPane, this.descriptionTab);
			this.descriptionTab.ShowAll ();
			// Container child infoNoteBook.Gtk.Notebook+NotebookChild
			this.logViewer = null;
			this.infoNoteBook.Add (this.logViewer);
			global::Gtk.Notebook.NotebookChild w3 = ((global::Gtk.Notebook.NotebookChild)(this.infoNoteBook [this.logViewer]));
			w3.Position = 2;
			// Notebook tab
			this.logLabel = new global::Gtk.Label ();
			this.logLabel.Name = "logLabel";
			this.logLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Logs");
			this.infoNoteBook.SetTabLabel (this.logViewer, this.logLabel);
			this.logLabel.ShowAll ();
			// Container child infoNoteBook.Gtk.Notebook+NotebookChild
			this.waypointWidget = null;
			this.infoNoteBook.Add (this.waypointWidget);
			global::Gtk.Notebook.NotebookChild w4 = ((global::Gtk.Notebook.NotebookChild)(this.infoNoteBook [this.waypointWidget]));
			w4.Position = 3;
			// Notebook tab
			this.waypointLabel = new global::Gtk.Label ();
			this.waypointLabel.Name = "waypointLabel";
			this.waypointLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Waypoints");
			this.infoNoteBook.SetTabLabel (this.waypointWidget, this.waypointLabel);
			this.waypointLabel.ShowAll ();
			// Container child infoNoteBook.Gtk.Notebook+NotebookChild
			this.cacheNotes = null;
			this.infoNoteBook.Add (this.cacheNotes);
			global::Gtk.Notebook.NotebookChild w5 = ((global::Gtk.Notebook.NotebookChild)(this.infoNoteBook [this.cacheNotes]));
			w5.Position = 4;
			// Notebook tab
			this.notesLabel = new global::Gtk.Label ();
			this.notesLabel.Name = "notesLabel";
			this.notesLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Notes");
			this.infoNoteBook.SetTabLabel (this.cacheNotes, this.notesLabel);
			this.notesLabel.ShowAll ();
			// Container child infoNoteBook.Gtk.Notebook+NotebookChild
			this.imageWidget = null;
			this.infoNoteBook.Add (this.imageWidget);
			global::Gtk.Notebook.NotebookChild w6 = ((global::Gtk.Notebook.NotebookChild)(this.infoNoteBook [this.imageWidget]));
			w6.Position = 5;
			// Notebook tab
			this.imageLabel = new global::Gtk.Label ();
			this.imageLabel.Name = "imageLabel";
			this.imageLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Images");
			this.infoNoteBook.SetTabLabel (this.imageWidget, this.imageLabel);
			this.imageLabel.ShowAll ();
			this.Add (this.infoNoteBook);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
