// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ocmgtk {
    
    
    public partial class ExportProgressDialog {
        
        private Gtk.Label label1;
        
        private Gtk.Label fileLabel;
        
        private Gtk.ProgressBar writeProgress;
        
        private Gtk.Label infoLabel;
        
        private Gtk.Button buttonCancel;
        
        private Gtk.Button okButton;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ocmgtk.ExportProgressDialog
            this.WidthRequest = 400;
            this.Name = "ocmgtk.ExportProgressDialog";
            this.Title = Mono.Unix.Catalog.GetString("Saving File...");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.Modal = true;
            this.BorderWidth = ((uint)(6));
            this.Resizable = false;
            this.AllowGrow = false;
            this.SkipPagerHint = true;
            // Internal child ocmgtk.ExportProgressDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.Spacing = 6;
            w1.BorderWidth = ((uint)(6));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.Xalign = 0F;
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("<big><b>Generating GPX File</b></big>");
            this.label1.UseMarkup = true;
            w1.Add(this.label1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(w1[this.label1]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            w2.Padding = ((uint)(6));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.fileLabel = new Gtk.Label();
            this.fileLabel.Name = "fileLabel";
            this.fileLabel.Xalign = 0F;
            this.fileLabel.LabelProp = Mono.Unix.Catalog.GetString("<b>File:</b>");
            this.fileLabel.UseMarkup = true;
            w1.Add(this.fileLabel);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(w1[this.fileLabel]));
            w3.Position = 1;
            w3.Expand = false;
            w3.Fill = false;
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.writeProgress = new Gtk.ProgressBar();
            this.writeProgress.Name = "writeProgress";
            this.writeProgress.Text = "0%";
            w1.Add(this.writeProgress);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(w1[this.writeProgress]));
            w4.Position = 2;
            w4.Expand = false;
            w4.Fill = false;
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.infoLabel = new Gtk.Label();
            this.infoLabel.Name = "infoLabel";
            this.infoLabel.Xalign = 0F;
            this.infoLabel.LabelProp = Mono.Unix.Catalog.GetString("<i>Intializing</i>");
            this.infoLabel.UseMarkup = true;
            w1.Add(this.infoLabel);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(w1[this.infoLabel]));
            w5.Position = 3;
            w5.Expand = false;
            w5.Fill = false;
            // Internal child ocmgtk.ExportProgressDialog.ActionArea
            Gtk.HButtonBox w6 = this.ActionArea;
            w6.Name = "dialog1_ActionArea";
            w6.Spacing = 10;
            w6.BorderWidth = ((uint)(5));
            w6.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonCancel = new Gtk.Button();
            this.buttonCancel.CanDefault = true;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseStock = true;
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = "gtk-cancel";
            this.AddActionWidget(this.buttonCancel, -6);
            Gtk.ButtonBox.ButtonBoxChild w7 = ((Gtk.ButtonBox.ButtonBoxChild)(w6[this.buttonCancel]));
            w7.Expand = false;
            w7.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.okButton = new Gtk.Button();
            this.okButton.Sensitive = false;
            this.okButton.CanDefault = true;
            this.okButton.CanFocus = true;
            this.okButton.Name = "okButton";
            this.okButton.UseStock = true;
            this.okButton.UseUnderline = true;
            this.okButton.Label = "gtk-ok";
            this.AddActionWidget(this.okButton, -5);
            Gtk.ButtonBox.ButtonBoxChild w8 = ((Gtk.ButtonBox.ButtonBoxChild)(w6[this.okButton]));
            w8.Position = 1;
            w8.Expand = false;
            w8.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 412;
            this.DefaultHeight = 225;
            this.okButton.Hide();
            this.Show();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
            this.buttonCancel.Clicked += new System.EventHandler(this.OnCancel);
            this.okButton.Clicked += new System.EventHandler(this.OnOKClicked);
        }
    }
}
